### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by Vexatos** [Tropicraft/Tropicraft#10]
I really would like this mod to support localizations. That would help people not playing Minecraft in English a lot.

I would translate it into the German language if it was added.

**Comment by Adaptivity** [comment]
And it is done now :smile:

**Comment by Adaptivity** [comment]
Also, you should create a repo for localization. Like this: https://github.com/CovertJaguar/Railcraft-Localization or this https://github.com/ForestryMC/Forestry-Localization Can't promise that I translate your mod but maybe sometime.

**Comment by Cojomax99** [comment]
Yes, I agree. We will do that soon.

**Comment by Adaptivity** [comment]
Can be closed since you are released the source and localizations can go through directly into it, it is the best way to support localizations.

**Comment by Vexatos** [comment]
Yup. Thank you all! :+1: :palm_tree:
