### ISSUE TITLE
Idea: bamboo ladders

### ISSUE THREAD

**Issue by cbaakman** [Tropicraft/Tropicraft#102]
There are many things that can be made from bamboo chutes/sticks: fences, chests, pots, item frames. However, the ladders are still plain wood. It would be cool to have ladders, made from bamboo sticks.

**Comment by Opiwaran** [comment]
Good idea, they should do that.

**Comment by Cojomax99** [comment]
This idea has been added to our internal backlog. Great idea, thanks for the suggestion!
