### ISSUE TITLE
Marlin fish stop AI and no return water after jump(surfacing)

### ISSUE THREAD

**Issue by Bogdan-G** [Tropicraft/Tropicraft#115]
Hello. MC 1.7.10, Forge 1614, TC 6.0.6(offic github repo)/6.0.5, CoroUtil 1.1.5(offic github repo), no optifine, no fastcraft
Over time, the fish surfacing, after which it turns off AI, fish perceives itself as the solid surface of the water, only a part of the nose it can return to the water (why?), if it is to push the fish will move in the direction that was made push.
![](https://pp.vk.me/c631625/v631625145/3e58f/5WYzKPsIffo.jpg)

PS if need, im create video.

**Comment by Cojomax99** [comment]
We are aware of this bug...however I have not had a chance to thoroughly investigate it.

**Comment by Bogdan-G** [comment]
I dug in the code, after the jump does not return the generation of movements, and the water becomes solid for the fish. Class: `net\tropicraft\entity\underdasea\EntityMarlin.java`
judging from the parts left when something is done, but then all the fish up in the air at 50(Y), Well and it goes without water damage (choking? but relatively quickly)

**Comment by Cojomax99** [comment]
This has been addressed in our upcoming release! Also, it did use a second texture, it was just very rare and handled outside the entity class, iirc ;)
