### ISSUE TITLE
Server Crash - Tropics worldgen

### ISSUE THREAD

**Issue by ProsperCraft** [Tropicraft/Tropicraft#118]
https://gist.github.com/ProsperCraft/a79d8751ee1c4342e431086344f82a89

NoSuchMethodError: CoroUtil.world.WorldDirector.addTickingLocation(LCoroUtil/world/location/ManagedLocation;)V

This might be due to the fact that I updated Coroutils.

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/3c23ae35717f81fab7362c502b7c0c87

Happened again.

**Comment by Cojomax99** [comment]
Perhaps you were using an incompatible version of CoroUtil with Tropicraft. Hard to know now as it is outdated. We are not using CoroUtil in our 1.10.2 release, so it should not give you the same problems :)
