### ISSUE TITLE
I don't know where said "coconut bomb whitelist" is

### ISSUE THREAD

**Issue by tigersnark** [Tropicraft/Tropicraft#120]
Every time I try to use the coconut bomb, it says for me to find a "coconut bomb whitelist" in the tropicraft config file, but I can't configure my mods in minecraft, and I can't find anything else that is a config file in tropicraft...PLEASE HELP!!!!

**Comment by Cojomax99** [comment]
For those looking for an answer to this, it's in the Tropicraft config file. Alternatively, you can access it in-game by typing the command "/config" then looking for the Tropicraft config and changing the option for 'coconut bomb whitelist'
