### ISSUE TITLE
My volcanoes aren't erupting (Tropicraft 1.7.10)

### ISSUE THREAD

**Issue by tigersnark** [Tropicraft/Tropicraft#121]
I waited for a long time and for some reason my volcanoes that I found aren't erupting.
I know that you (Cojo) are trying to update the mod to 1.9.4. But if you have any extra time on your hands, can you please fix this in 1.7.10, also, when you do update it's version can you try to make sure this doesn't happen again in 1.9.4, thanks ;)

**Comment by AGiLE-EaGLE1994** [comment]
I'm pretty sure 1.2.5 is the last version where volcanoes erupted. That was in 2012.

**Comment by Cojomax99** [comment]
There have not been eruptions for many, many moons. 1.10.2 re-adds eruptions. Enjoy :)

**Comment by tigersnark** [comment]
Do I need any other mods like weather mod to make them erupt?

**Comment by CitiesXL2815** [comment]
dude you don't need any mod to have them erupt, there removed to erupt earlier version before 1.7.10 too much terrain destruction so that is why they do not erupt, if you want to have them erupt go to 1.10.2 where they do erupt

**Comment by tigersnark** [comment]
Thank you! I hope I actually get lucky enough to see one erupt, though
