### ISSUE TITLE
Mahogany Leaves dropping Spruce saplings

### ISSUE THREAD

**Issue by jdm987** [Tropicraft/Tropicraft#122]
I had this problem without any other mods to cause an I.D. or other conflict. I mined around 200 mahogany leaf blocks and the ones that did drop saplings only dropped spruce saplings. Thanks for the help.
*EDIT*
I have installed waila just so I can show that it is the mahogany leaves
![2017-02-12_15 48 08](https://cloud.githubusercontent.com/assets/25729041/22866365/00fb3f0a-f13b-11e6-8741-5520ca148305.png)

**Comment by Bogdan-G** [comment]
mod/forge/game versions?
