### ISSUE TITLE
Bug: Crash when near volcano w/ Local Weather mod installed

### ISSUE THREAD

**Issue by darthvader45** [Tropicraft/Tropicraft#124]
Every time I go near a volcano in the Tropicraft dimension with Corosus' Local Weather and Storms installed, it kicks me from my game, and any attempt to re-enter the save crashes my game.  Might want to look into it.

How to replicate:
Have both mods installed, go to the tropical dimension, go near a volcano (might recommend a mini map to locate one more easily).

**Comment by Cojomax99** [comment]
Unless you have a crash report, we can't really help unfortunately. Feel free to comment with a crash report and I'll re-open this!

**Comment by darthvader45** [comment]
@Cojomax99 Found out the problem, it was the coroutil provided with the Tropicraft download for 1.7.10.  CoroUtil updated to 1.1.6, and the one in the Tropicraft 1.7.10 download is 1.1.3, which is out-of-date.
