### ISSUE TITLE
Frogs Spawning too much, plz help

### ISSUE THREAD

**Issue by CacheTellsStories** [Tropicraft/Tropicraft#135]
So in the overworld when I find a tropical biome there are hundreds of frogs. No matter how much I kill, they just keep spawning. Does anyone have a fix?

**Comment by Cojomax99** [comment]
Not for 1.7.10. Unfortunately we aren't working on that version anymore :/

**Comment by Cojomax99** [comment]
This is fixed in the upcoming release. Closing this as we're no longer supporting bug fixes on our 1.7.10 branch.
