### ISSUE TITLE
Koa Villages Are Not Spawning.

### ISSUE THREAD

**Issue by RZJtc** [Tropicraft/Tropicraft#138]
In Tropicraft 6.0.0 (release 1.7.10), it doesn't seem that Koa Villages spawn. I went in every direction about 2000 blocks out and couldn't find anything besides boat wrecks, volcanos, and little platforms with chairs on them. I put all the mods from the zip file into my mods folder (and the schematic for the Koa Village), and ran them with forge 1.7.10-1448 and they didn't spawn. I was curious to see if you are currently working on this problem on Tropicraft 6.0.0, or if you are fixing it on 1.9.4. Thank you.

**Comment by Opiwaran** [comment]
You have to place the folder with the schematic into your minecraft folder.

**Comment by IvanSokolovBG** [comment]
Refer to this topic. -> https://github.com/Tropicraft/Tropicraft/issues/108
IMPORTANT: NOT a fix. Some information on the problem.

**Comment by Cojomax99** [comment]
If the same issue occurs in 1.10.2, please let us know. Sorry for this issue! :(
