### ISSUE TITLE
No tropical fish, no monkeys, and several other issues

### ISSUE THREAD

**Issue by Opiwaran** [Tropicraft/Tropicraft#139]
I have recently reinstalled Minecraft after I had some other issues and now installed the recommended forge version, downloaded the 6.0.5 version of tropicraft, placed the contents of the mods folder from the zip into my mods folder and also put the TCShematics folder into my .minecraft folder. I have not installed any other mods since then. It now says I have 9 mods loaded and active which I guess is right.
But I have several issues that I can't explain:

- There are no small fish or monkeys to be seen anywhere. I do get marlins, turtles and mantas occasionally, but no small tropics-fish and no monkeys which I remember were part of the mod back in 1.6.4 times.
- Are there supposed to be so many Iguanas? I often find them in groups of 20 and more, and those groups aren't rare.
- I can't place any shells/starfish on the wall (you are supposed to right click, right?)
- I can't pick up dropped Ashen masks (rightclicking does nothing, an empty inventory does nothing, leftclicking destroys them without a drop)
- Aren't there supposed to be waves/weather effects? (This is a genuine question, I only remember vaguely)
- Should the frogs be moving at near supersonic speed? I remember them being a bit more reasonable paced. I don't know if this is an issue or a new feature to make them more of a threat (and annoying)
- The marlins only float on top of the water and do nothing, even when attacked.

I really hope someone can help me with these issues, I love this mod so much <3

**Comment by Cojomax99** [comment]
These all should be fixed in 1.10.2. If they're not, let me know!
