### ISSUE TITLE
SMP missing mod/can't connect (It's a lie...I don't get it)

### ISSUE THREAD

**Issue by Pwnsaucier** [Tropicraft/Tropicraft#14]
Tropicraft 5.1.7 (from the install package on the website http://tropicraft.net/downloads/)
Weather v1.591
Forge 965
Also in MCPC+ 251

When trying to connect to a MP server running forge or MCPC+ versions listed above with only the mods ConfigMod, CoroUtil, ExtendedRenderer, ModBuild, Tropicraft, and Weather installed, using a client with the exact same mods (verified/recopied multiple times), the client fails to connect with message: http://i.imgur.com/xcssWWk.jpg

Forge Mod Loader could not connect to this server
The mods and versions listed below could not be found
They are required to play on this server
WeatherMod: 1.591

This makes no sense...the files on both the client and server are identical.
Also, the mod shows up in the client's mod list http://i.imgur.com/ovN1MKp.jpg

I don't get it.

**Comment by Cojomax99** [comment]
Corosus fixed this, I guess.
