### ISSUE TITLE
Waaaay too many Failgulls

### ISSUE THREAD

**Issue by ProsperCraft** [Tropicraft/Tropicraft#140]
https://gyazo.com/d014524cedb588974b93e495d7869ab2

That kill command killed 2849 of them, then 682 more.    Then 600 more 10 minutes later.

 I got involved because a user could not log in because there were too many of them.

Can you put a check in to keep them from spawning thousands of them?

Modpack - https://minecraft.curseforge.com/projects/drtardis-adventure-modpack

**Comment by Cojomax99** [comment]
I haven't seen that issue with failgulls before, only tropics fish. Not really sure what happened there, but it's probably another mod messing with the spawning mechanisms.

**Comment by Cojomax99** [comment]
Mob spawning is fixed in the 1.10.2 release. Sorry about our insane 1.7.10 spawning!

**Comment by ProsperCraft** [comment]
My 1.7.10 modpack starts in the tropics, could you please backport the spawning fix?

I have a couple years work into this modpack.

**Comment by DarleenDolphin1** [comment]
I ran... a flock of failgulls...
