### ISSUE TITLE
List of Bugs in Tropicraft v5.1.7

### ISSUE THREAD

**Issue by Gahshunk** [Tropicraft/Tropicraft#15]
-When using half slabs in the mod, such as bamboo, they break in a single punch when they are top half slabs. The bottom slabs and two slabs connected to make one block appear to interact normally and accordingly to the axes/fist used.

-Starfish seem to drown, regardless of being on land or water.

-There seems to be a problem with tropical fish spawning using their egg. They spawn 3 or 4 blocks away from where one used the fish eggs. Another particular glitch is that the tropical fish will only spawn in a single location once you start interacting with them, such as spawning or catching them in a bucket then releasing them. Actually, all aquatic mobs seem to stop spawning with time.

-The blow dart's potion effects appear non-existent. Notably, only the first dart that hits an entity will inflict damage. Subsequent darts shot at the same entity seem to miss or bounce off entirely.

-I've yet to see a sea star, man-o-war, urchin, or turtle spawn naturally.

-Planting Iris' causes their heads to pop off.

-Sugar cane appears to grow at a painfully slow rate using this mod. Unsure if this is a result of Spigot (MCPC+) or it's the actual mod.

-Are Eudialyte and Zircon tools suppose to be less efficient than stone or iron tools?

-Spamming a stack of buckets on the tropical water results in the creation of regular water found in the overworld.

-(Suggestion) Bamboo spears are as powerful as iron swords. That seems slightly broken. Any chance of lowering the damage output? And Daggers are only as good as your fist.

 As a side note, congratulations on fixing the Koa villagers. Very lovely update.

**Comment by Cojomax99** [comment]
These seem to be fixed in the upcoming 1.10.2 release. Feel free to create separate issues for each of these you find that are still bugs.
