### ISSUE TITLE
Snare Crash Thermos 1558 server

### ISSUE THREAD

**Issue by voidswrath** [Tropicraft/Tropicraft#159]
https://pastebin.com/zVcrZKD5

**Comment by NotActuallyTerry** [comment]
Closing as 1.7.10 is no longer supported, and Thermos has been discontinued.

**Comment by voidswrath** [comment]
cold as ice

**Comment by Cojomax99** [comment]
We may do a pass through on 1.7.10 eventually. If we do, we will let you know. Not sure what to do if it's a Thermos issue, though.
