### ISSUE TITLE
Tropicraft water and OpenBlocks Tank crash.

### ISSUE THREAD

**Issue by Ixirim** [Tropicraft/Tropicraft#18]
So whenever someone puts water from the Tropicraft realm into an OpenBlocks Tank, the client will crash.

Crash log: http://pastebin.com/timxrgpt

**Comment by ajloveslily14** [comment]
That seems to be on OpenBlocksside, not Tropicrafts.(i could be wrong though) :flushed:

**Comment by Cojomax99** [comment]
Will need someone to confirm this in the upcoming release.

**Comment by Adaptivity** [comment]
I can't pour tropics water in OpenBlocks Tank by simple right-clicking. Fluids from other mods works flawlessly.

**Comment by JAWSAWN** [comment]
Having similar problem like this
https://github.com/Tropicraft/Tropicraft/issues/28

**Comment by Cojomax99** [comment]
This will be fixed in the upcoming release v6.0.3.
