### ISSUE TITLE
Tropic Water Bug(s)

### ISSUE THREAD

**Issue by 4104** [Tropicraft/Tropicraft#180]
When messing around in tropicraft 1.7.10, I have noticed that Tropic Water can't be made into an infinite water source. I'm not sure if this is an issue or a feature. Tropic water can also be blown up, unlike normal water or lava. I was just wondering if this would be fixed in the new 1.10 Tropicraft.

Cheers mate,

**Comment by okushama** [comment]
will be sorted for the next build, thank you for highlighting this to us.
