### ISSUE TITLE
LostMask Spam

### ISSUE THREAD

**Issue by Nightreaver** [Tropicraft/Tropicraft#185]
Hello

I am using tropicraft-6.0.5 for 1.7.10

And im having a monster spawner with corrupted earth.

As the spawner is also spawning ashen hunter, it have plenty of masks that do not disappear at all.
So after a certain time my server is dying with more than 6000 masks laying around.
I even cannot kill the masks with kill command. 

How can I stop lost-mask from dropping?
I want to disable either ashen hunter or the "lostmask".

Please advise

Cheers

**Comment by NotActuallyTerry** [comment]
Closing issue as 1.7.10 is no longer supported
