### ISSUE TITLE
Portal changes world spawn

### ISSUE THREAD

**Issue by recon88** [Tropicraft/Tropicraft#19]
Whenever a new portal is created, it sets the spawnpoint to that.
I was reading ( http://tropicraft.net/p/bug-fixes-b-team-and-more/ ) that this was fixed in 5.1.7 but it isn't. I'm running that version and users keep complaining everyday that they spawn at Tropicraft Portals when they die.

**Comment by Cojomax99** [comment]
Fixed in #64
