### ISSUE TITLE
Crash on Server Start-up

### ISSUE THREAD

**Issue by spruill7716** [Tropicraft/Tropicraft#22]
Not really much to say here. Maybe some kind of compatibility error?
https://www.dropbox.com/s/rre8pqsqk6kma90/crash-2015-04-13_17.02.01-server.txt?dl=0

**Comment by Cojomax99** [comment]
What did you do to have this happen?

**Comment by rckymtnrfc** [comment]
I get the same thing.  It's on server start-up, not on any particular action.

**Comment by Cojomax99** [comment]
Fixed in v6.0.2.
