### ISSUE TITLE
Compatibility issues with Mo' Creatures and Custom Mob Spawner

### ISSUE THREAD

**Issue by okushama** [Tropicraft/Tropicraft#222]
From user Xhale on discord:

> A quick glance shows that having Mo' Creatures and Custom Mob Spawner installed might screw with Tropicraft mobs. As in neither tropicraft mobs nor Mo' Creatures mobs spawn. I'm sure this is a problem on their side, but maybe some collaboration could fix that...

**Comment by 0Navis0** [comment]
It's well known Mo'Creatures and especially Custom Mob Spawner messes all other mods mobs. This mod is pretty solitary, it doesn't get along with others, definitely not made for modpacks. The devs never did anything for solving it.
