### ISSUE TITLE
No mobs in tropicraft dimension

### ISSUE THREAD

**Issue by Lajtmen** [Tropicraft/Tropicraft#225]
There are no mobs expect for that tropicraft villagers , any advice ? :D I have custom spawner mod (i dont know if does matter)

**Comment by okushama** [comment]
Tropicraft uses a custom spawn system which is probably being broken, could you please link the custom spawner mod you spoke of? It's likely causing issues.

**Comment by Lajtmen** [comment]
http://www.9minecraft.net/custom-mob-spawner-mod/

**Comment by Cojomax99** [comment]
You shouldn't use 9minecraft for any mods you get, it is not a reputable site for finding mod downloads. Anyway, it is very likely that mod is breaking our custom spawn system for our mobs, yep.
