### ISSUE TITLE
Cant open dimension 1.10.2

### ISSUE THREAD

**Issue by amandabar** [Tropicraft/Tropicraft#227]
every time I try to go into the dimension it crashes my minecraft and yes I have other mods. How can I fix this?!

**Comment by vadis365** [comment]
Have you tried turning it off and on again?

**Comment by Killer-Demon** [comment]
Did you try working the shaft?

**Comment by amandabar** [comment]
What do you mean? @Killer-Demon

**Comment by amandabar** [comment]
You mean going in and out of the game? @vadis365

**Comment by Andromander** [comment]
Have you tried uploading a crash log?

**Comment by Cojomax99** [comment]
Yep, we need a crash log for this.

**Comment by amandabar** [comment]
How do I do that? @Cojomax99

**Comment by Cojomax99** [comment]
See if this guide helps you get it https://imgur.com/a/N7sQD

**Comment by amandabar** [comment]
I did that. What do I do next? @Cojomax99

**Comment by Cojomax99** [comment]
Post the link to the pastebin in here :)

**Comment by amandabar** [comment]
Ok, here it is https://paste.ubuntu.com/p/MvxS8v3Mfz/ @Cojomax99

**Comment by tterrag1098** [comment]
Sorry, that log doesn't show anything. Can you find your `crash-reports` folder and give the latest file there?

**Comment by amandabar** [comment]
Try this https://paste.ubuntu.com/p/FWvfQydhQB/ @tterrag1098 @Cojomax99

**Comment by tterrag1098** [comment]
Seems to be an error from Mo' Creatures ?

**Comment by amandabar** [comment]
I removed mo creatures from the mod folder and it still wont work. Here is the log without mo creatures in my folder > https://paste.ubuntu.com/p/w93C4hHkx4/ @tterrag1098 @Cojomax99

**Comment by tterrag1098** [comment]
This crash log *only* has Mo' Creatures in it, not even Tropicraft.

```
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAAAA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAAAA	MoCreatures{8.0.1} [DrZhark's Mo'Creatures Mod] (Mo'Creatures Mod-8.0.1 (1).jar) 
```

**Comment by amandabar** [comment]
Then what am I supposed to do? @tterrag1098 @Cojomax99

**Comment by Cojomax99** [comment]
This seems like an issue with Mo' Creatures. You should contact DrZhark with this report. Alternatively, if you remove Mo' Creatures and add Tropicraft and it still crashes, post that log here. But from your crash log it seems you have only removed Tropicraft, not Mo' Creatures.

**Comment by NotActuallyTerry** [comment]
Issue seems to lie with Mo' Creatures, no response from issue reporter. Closing.
