### ISSUE TITLE
The Tropical Villagers won't trade!!!

### ISSUE THREAD

**Issue by MadHatterMooCow** [Tropicraft/Tropicraft#228]
I also have a problem with no mobs. Sure I can spawn them with a egg but they won't spawn naturally, except for the villagers, which brings me to a unreported problem I have... THEY WON'T TRADE! I "right-click" (in quotes because i'm on a Macbook and it's hard to right-click so I changed the button) on the villager and it says in the console, "you still need 60 more minutes of dive time! No trimix gas for you!". Please help.

**Comment by Cojomax99** [comment]
There is no villager trading in 1.10.2 currently. The villagers will give you a trimix gas for your scuba gear if you right click them with your dive computer and you have been underwater with your scuba gear on for 60 minutes IRL time.
