### ISSUE TITLE
Page 8 of Encyclopedia Tropica causes Crash

### ISSUE THREAD

**Issue by DiamondCreeper** [Tropicraft/Tropicraft#23]
I was attempting, per usual, to fill out the Encyclopedia, but when I got to Page 8, it crashed. I tried three more times and it repeated exactly the same.

**Comment by Cojomax99** [comment]
Can you paste a crashlog please?

**Comment by Adaptivity** [comment]
http://pastebin.com/nMKbv2d3

**Comment by Cojomax99** [comment]
This was an issue with how I handled tall flowers. This will be fixed in v6.0.3.
