### ISSUE TITLE
HWYLA crashes game upon looking at a pineapple. [1.12.2 because I am impatient]

### ISSUE THREAD

**Issue by GrucciNishikino** [Tropicraft/Tropicraft#230]
I am playing the 1.12.2 build of the mod, but I have experienced an issue in which the game crashes when I look at a pineapple using the WAILA fork, HWYLA. The crash report is found [here.](https://pastebin.com/9M0WFHrm)
Forge version 14.23.1.2604, Tropicraft 7.1.0.42 from your jenkins server, and HWYLA version 1.8.23-B38

**Comment by Cojomax99** [comment]
You got the beta before it was ready ;) Thanks for the report, will check again when we have a stable beta to see if this is still an issue.

**Comment by GrucciNishikino** [comment]
I have read the HWYLA issues, and it seems that the issue is with the bottom half of the pineapple, but it crashes if I look at either one. Just some words for when this is looked at again.

**Comment by GrucciNishikino** [comment]
I checked the jenkins server today, and found a wonderful surprise! Thank you for addressing this issue,
