### ISSUE TITLE
Crash directly after another Crash (server crash)

### ISSUE THREAD

**Issue by TheGameAce** [Tropicraft/Tropicraft#231]
Here's the crash log;
https://pastebin.com/NJVDXDyQ

I've noticed this happens directly after anything else causes a crash. Seems to be that if the chunk(s) with fish (in this case, in the overworld in a tank) are loaded (chunkloader, player joining back before others), directly after a crash, anyone joining and causing the chunks to load causes another crash.
Pardon if this is a noticed issue or something that can't be resolved currently, but it's late night and I wanted to quickly get this posted.

**Comment by TheGameAce** [comment]
Also wanted to note I've noticed some other issues. One, namely, is that apparently while fish are in the overworld, squids won't spawn anywhere.

**Comment by Cojomax99** [comment]
Hm, that's super weird, who knew our fish had those kinds of superpowers. I'll look into that.

**Comment by TheGameAce** [comment]
Awesome! Hope a fix can be gotten out for this at some point soon :P I've had to kill all the fish (and other aquatic mobs too now, because they can do it as well, apparently) in my tank because it was driving everyone crazy with the crashes.
Great mod nonetheless, and an all-time favorite for me. Keep up the good work! :)

**Comment by Corosauce** [comment]
For info sake, this is currently fixed in 1.12 but not 1.10
