### ISSUE TITLE
Fish stuck at bottom of tank?

### ISSUE THREAD

**Issue by nullcasting** [Tropicraft/Tropicraft#232]
Hi y'all,
I've been trying to build a pretty sizeable fishtank in tropicraft, but I've been running into an issue. The fish that I put in the water / spawn in seem to stay on the very bottom of the tank, sometimes pooling into one corner. Is this just how they behave, is this a bug, or is this something I'm messing up?

**Comment by Cojomax99** [comment]
Probably a bug. The problem wish fishies is they like to look ahead to determine where to swim, and when there isn't much space, they may get stuck. We'll look into it, but it's a bit of a tricky problem to solve with water mobs especially.

**Comment by tterrag1098** [comment]
A temporary solution I found is to make sure you don't build the tank near a large body of water. That way they don't try to swim towards an ocean they can't reach, which is what causes this issue.
