### ISSUE TITLE
Can't join/create worlds.

### ISSUE THREAD

**Issue by Zalthrion** [Tropicraft/Tropicraft#24]
Hello, I had been receiving an exception on the console that wouldn't allow the user to create new worlds nor join them, this happened when I added Tropicraft to a private mod pack.

This exception started to happen after I added Tropicraft to the pack, I did verify it was Tropicraft by removing the mod and trying to create/join a new world without it. 

Here are the logs for the exception:

http://pastebin.com/V7ErqZiS

I hope this is enough. Thanks, and keep doing such a great job! =D

**Comment by Adaptivity** [comment]
Can confirm this too. Removing Thermal Expansion fixes the problem, not sure on which side problem is.

**Comment by Cojomax99** [comment]
That's odd. I'll talk to the devs and see what they say. Thanks!

**Comment by Cojomax99** [comment]
Looks like it has to do with the names of our blocks and items in the ore dict. Should be camelCase. Will fix this when I can.

**Comment by Cojomax99** [comment]
This is fixed in v6.0.3.
