### ISSUE TITLE
1.12.2 number of small issues

### ISSUE THREAD

**Issue by Zygus42** [Tropicraft/Tropicraft#240]
Tropicraft - 7.1.0.50

You probably already have most of these on your todo list, but here some are:

- [ ] Can't drink Piña Coladas (or any of the other drinks).  Managed to get to the dimension with a Wand, but can't get back with the portal pool without drinking.

- [ ] Encyclopedia has headings but no contents.

- [ ] No idea how to use certain things like the scuba gear - guess the Encyclopedia might help with that, otherwise some instructional tooltips would be great.

- [ ] I know you have the Encyclopedia, but some tooltips on items like the Sifter to give a quick idea of what it does would be great.

- [ ] Hammerhead sharks have a tendency to beach themselves and die.

- [ ] No config for the amount of bamboo that spawns in Overworld.

- [ ] Thought the Iguana Leather was a fern and almost threw it away :)  Odd icon for a leather product.

- [ ] Drink Mixer is identical to Air Compressor - confusing, but could be very funny to suddenly find yourself breathing Coffee instead of Air.

Gorgeous world spawn in tropics dimension !!!  Very well done.  Maybe add a few more waterfalls.

**Comment by Cojomax99** [comment]
Thanks for your comments! Several of these have now been addressed. About pina coladas - are you in creative mode when you are trying to drink? Full hunger?

**Comment by Zygus42** [comment]
1) You are correct - drinking does not work in creative mode.  Retested it in Survival mode and drinking and portaling there and back were just fine.

9) This is what I found when I came back though - it made a giant long pier out of thatch and sunk my chair and umbrella.  Is that pier meant to happen ?  Might want to offset the pool a few blocks so the chair and umbrella are placed next to the pool.

![2018-03-19_18 22 39](https://user-images.githubusercontent.com/20757445/37590283-c098e1ee-2ba2-11e8-88c9-a4eccb49b35a.png)

10)  I came out near a village, and could see careers on the villagers which were clearly not correct - maybe an issue with Hwyla ?

![2018-03-19_18 30 00](https://user-images.githubusercontent.com/20757445/37591081-4b234230-2ba5-11e8-9679-e09d59abb2ec.png)


11)  All of the villagers with swords leapt into the water and got themselves killed by Iguanas.  Do they respawn ?  If not, may want to give them a damage upgrade.

12)  The Coconuts Leaves are not decaying and Coconuts are not falling down.

![2018-03-19_18 42 04](https://user-images.githubusercontent.com/20757445/37591121-651e513e-2ba5-11e8-9848-c85754b17e82.png)

**Comment by Corosauce** [comment]
Hmmm will probably have to soft depend on Hwyla and override what it shows, koa dont use careers and professions but the data is there for other mods to see I guess, actually working with villager careers and professions is a huge pain in the ass. Or I could just stop extending EntityVillager i guess, can't remember the benefits to that atm.

**Comment by Zygus42** [comment]
Couldn't just set their professions to "Islander" or something along those lines ?  No really big deal either way - hardly game breaking :)

**Comment by Cojomax99** [comment]
Unfortunately setting a career is not as trivial as we might like, so it probably won't be on our radar for a bit. We are looking into some of the other issues you mentioned, but many have been fixed in 7.1.1 and 7.1.2!

**Comment by Corosauce** [comment]
Koa displaying is now fixed in a dev branch, shows gender and tropicraft koa role, tested with TheOneProbe, i figure it'll be fixed with other mods too: 
![2018-04-11_20 52 06](https://user-images.githubusercontent.com/1238621/38650702-4da6aabe-3dcb-11e8-9de0-19505278e424.png)

**Comment by tterrag1098** [comment]
Closing as most of these seem to be fixed/intended. Please comment if any are not.
