### ISSUE TITLE
No Pineapples in my World

### ISSUE THREAD

**Issue by Immaculala** [Tropicraft/Tropicraft#246]
I have just installed this mod and couldn’t find any Pineapples. So I made a Creative world and spawned Pineapples, and all it spawned were the stalks. WAILA gave me one of those black & purple boxes when I hovered over the plant.

tropicraft-MC1.10.2-7.0.3.145
Forge 1.10.2 - 12.18.3.2185
Waila-1.7.0-B3_1.9.4
jei_1.10.2-3.14.7.420

Can anyone help?
<img width="626" alt="no pineapples" src="https://user-images.githubusercontent.com/26187212/37656334-a52bcb90-2c3f-11e8-92f9-99773fea10bb.png">

**Comment by Cojomax99** [comment]
Hey, thanks for pointing these issues out! We have fixed them in v7.1.2 via https://github.com/Tropicraft/Tropicraft/commit/3e5624ecea5ee822adb2c1d9b166d39c0788589d and https://github.com/Tropicraft/Tropicraft/commit/d1337a5244a8cb80b82ba3bc571f33aa04cb1b31. Grab the new version at https://minecraft.curseforge.com/projects/tropicraft/files/2543741. Thanks!
