### ISSUE TITLE
Version 6.0.2 Bugs

### ISSUE THREAD

**Issue by InsaneNeko5** [Tropicraft/Tropicraft#25]
Bugs found in version 6.0.2 so far

1. The Iris flower can't be placed  and will sometimes just pop off the ground on it's own
4. Trying to go past page 7 in the encyclopedia crashes the game
6. Can't return to the overworld after going to the tropics
7. Pineapples aren't spawning in the overworld

I will continue to update this list as bugs are found and fixed
Forge and Tropicraft are the only mods installed

**Comment by Adaptivity** [comment]
3. can confirm.

**Comment by Cojomax99** [comment]
Thanks for the reports. Will get to these as soon as we can!

**Comment by Cojomax99** [comment]
Fixed issue 2: https://github.com/Tropicraft/Tropicraft/commit/7cded4fa5cf17f29f1e26c9090ae82ada84985b9

**Comment by InsaneNeko5** [comment]
Good job man, I look forward to doing bug hunting and squashing with you in the future.
