### ISSUE TITLE
Overworld amount of pineapple and bamboo

### ISSUE THREAD

**Issue by SmallSansSerif** [Tropicraft/Tropicraft#250]
Can you add something to reduce the spawn rate of bamboo and pineapple in the overworld so you can make them more rare? 

I like that I can reduce the grouping size of the bamboo but would like to make it more rare or isolate it to the beach like the palms can be.

**Comment by Immaculala** [comment]
If it's really irritating you I believe you can change it in the config file.

**Comment by SmallSansSerif** [comment]
What's the option to reduce the spawn frequency of those items in the overworld? I only saw options for reducing the size of bamboo groupings.

**Comment by Immaculala** [comment]
Sorry, I meant you can stop generation of all Trop items in the Overworld in the _tropicraft.cfg_ file.
Don't know how to just reduce it though.
I think you probably know more about it than I do.
