### ISSUE TITLE
About repost

### ISSUE THREAD

**Issue by forestbat** [Tropicraft/Tropicraft#251]
Hi，I‘m a translator and carrier in mcbbs in China。We all love your mod，but Great Fire Wall give us some trouble to download it，so we want carry the mod to mcbbs——we won't earn money from it and will recommend everyone download from curseforge。
Await your reply。

**Comment by Cojomax99** [comment]
Hello,

As long as all of the downloads are through CurseForge that is fine. I don't want anybody rehosting the download or any Tropicraft files, though. Thanks!
