### ISSUE TITLE
Client error: Cannot load encyclopedia outside of a save!

### ISSUE THREAD

**Issue by kencinder** [Tropicraft/Tropicraft#254]
Client times out when connecting to SMP, log(snippet) shows error linked to below.

Minecraft 1.12.2
Forge 14.23.2.2611
Tropicraft 7.1.2.57.

https://pastebin.com/yrcrTezh

Server running SpongeForge

**Comment by Sunconure11** [comment]
I can confirm something similar is happening without Sponge. It's crippling my server.

https://github.com/OreCruncher/DynamicSurroundings/issues/292

**Comment by tterrag1098** [comment]
Fixed via a9d361d6987da96676401e05ca37f1ff536c4ba3
