### ISSUE TITLE
Swimming is Broken

### ISSUE THREAD

**Issue by SirBlockles** [Tropicraft/Tropicraft#257]
When this mod is installed, swimming behavior tied to the scuba diving mechanic breaks regular swimming. Specifically, players can get stuck on the sea floor. This is most prevalent near the edge of a block, where players can get stuck on the block, not even able to fly out in Creative mode. Unless the player has a shovel on-hand, they'll end up drowning before they can break the block.

The mod also seems to think the player is continually sinking as they're stuck, leading their body to tilt downward continuously (as demonstrated in the attached image).

![javaw_2018-03-25_19-36-56](https://user-images.githubusercontent.com/3620019/37883842-15a3bd28-306a-11e8-9dc4-c8c8206d68c3.png)

**Comment by NotActuallyTerry** [comment]
Possibly fixed by 4947c1b, any testing to confirm this would be appreciated.
