### ISSUE TITLE
Palm leaves don't decay at all

### ISSUE THREAD

**Issue by Sunconure11** [Tropicraft/Tropicraft#258]
Furthermore, they aren't flammable.

This seems to apply to all leaves from this mod.

**Comment by KollinsPlays** [comment]
Can confirm they neither decay nor catch on fire. I did test a lot of Tropicraft blocks and it appears not being flammable is by design.

**Comment by Corosauce** [comment]
Flammable issue has been fixed but not released yet, the decay part is a more complicated problem...

**Comment by theBudster** [comment]
Not only do they not decay, but the leaves do not drop any saplings when broken

**Comment by NotActuallyTerry** [comment]
As it is leaves not decaying is "intended" (as otherwise they'd decay upon trees being generated, we'll be looking into rewriting logic for that for 1.13/1.14). However, saplings not dropping is definitely a bug. Could you open a new issue for it? @theBudster
