### ISSUE TITLE
Untextured Border Surrounding Volcano (and more)

### ISSUE THREAD

**Issue by Xhale1** [Tropicraft/Tropicraft#260]
I popped into the Tropics for some testing and spawned right next to a volcano. Surrounding the volcano, and a patch of seaweed, were untextured edges. Not full blocks, just edges. I'll include a screenshot.

Using Tropicraft 1.12.2 (7.1.3.62) and Forge (14.23.2.2639)

<img width="1680" alt="screen shot 2018-03-27 at 11 21 41 pm" src="https://user-images.githubusercontent.com/6383154/38009864-7bddd13a-3224-11e8-909f-b0d1e6821352.png">

**Comment by Cojomax99** [comment]
How much memory are you running the game with? And are you running any other mods? Have you tried running with the recommended version of forge (2611)?

**Comment by tterrag1098** [comment]
This is a known bug with CTM, when you add/remove a texture pack while ingame. Restarting the game should fix it.
