### ISSUE TITLE
Sleeping in the tropics does not advance time

### ISSUE THREAD

**Issue by Sunconure11** [Tropicraft/Tropicraft#261]
When one sleeps in the tropics, it simply progresses to the middle of the night in that dimension

**Comment by kencinder** [comment]
Could not duplicate this on my server. Set time to 8:00pm, placed bed, went to sleep, woke up at 6:00am with sun coming up.

forge-1.12.2-14.23.2.2611
SpongeForge 7.1.0-BETA-2990
Tropicraft 7.1.3.62

You sure someone didn't simply get out of bed in the middle of the night?

**Comment by Sunconure11** [comment]
One player is in the overworld while I'm in the tropics.

I do have morpheus installed, however.

**Comment by kencinder** [comment]
I've had trouble with Morpheus, in many ways. When it comes to dimensions, it's dev believes it's on dimension mod devs to support Morpheus, rather than Morpheus simply doing server-wide sleep or working per-dimension.
I would suggest SleepVote for Sponge if you are running Sponge. If Forge only...can't help ya.

**Comment by Sunconure11** [comment]
I'm not using Sponge, as it breaks several of the mods I use.

**Comment by kencinder** [comment]
Take Morpheus out of the equation and see if it still happens. I would bet it doesn't, and I highly recommend finding something else to handle sleep.

[This](https://github.com/Quetzi/Morpheus/issues/48) is the sort of thing I'm referring to. No dimension mod should have to add support for a sleep mod, for the sleep mod to behave properly in this case.

**Comment by superfluke** [comment]
Can confirm, time does not advance while sleeping in the tropics dim.
Single player, no morpheus, no sponge. 
forge-1.12.2-14.23.5.2768
tropicraft-MC1.12.2-7.1.8.105
