### ISSUE TITLE
Bamboo gen crashes the world

### ISSUE THREAD

**Issue by Sunconure11** [Tropicraft/Tropicraft#263]
## Issue Description

Upon generating a new world in SMP, I am greeted with a crash.

## Steps to Reproduce
1) Generate a world in SMP
2) ???
3) https://pastebin.com/jzT5nstn

Tropicraft Version:   7.1.3.62
Forge Version:   14.23.2.2652

## Crash log
```
https://pastebin.com/jzT5nstn
```

**Comment by Sunconure11** [comment]
It appears this is connected to editing bamboo gen rates, or the config in some way. This is the old config I used:

https://pastebin.com/AedrZtQe

**Comment by NotActuallyTerry** [comment]
Hi,
This issue is caused by a negative number being in the config. As it's a percentage chance for it to spawn, having a negative number would naturally not work.

**Comment by Sunconure11** [comment]
By default, the chance for palms to spawn is set to -1, in a clean config. Clearing the old config fixed this though, even though I was not using a negative number.

**Comment by NotActuallyTerry** [comment]
Hi again,

My bad, jumped the gun a bit. This error is actually caused by I:maxBambooPerPatchOverworld being higher than I:minBambooPerPatchOverworld, as the min value is taken from the max value as seen here. https://github.com/Tropicraft/Tropicraft/blob/e4195dcd2fcf2dd3aa69970a086f6f2e28097a77/src/main/java/net/tropicraft/core/common/worldgen/WorldGenBamboo.java#L43

**Comment by evhub** [comment]
With the config
```
generation {
    B:genBambooInOverworld=true
    B:genOverworldPalmsInBeachOnly=false
    B:genPalmsInOverworld=true
    B:genPineapplesInOverworld=true
    B:genTropicraftEIHInOverworld=true
    B:genTropicraftFlowersInOverworld=true

    # If false, no Tropicraft generation will occur at all in the overworld.
    B:genTropicraftInOverworld=true
    I:maxBambooPerPatchOverworld=30
    I:maxBambooPerPatchTropics=120
    I:minBambooPerPatchOverworld=10
    I:minBambooPerPatchTropics=60
    I:palmChanceOfGenInOverworld=-1
    I:palmPopulationFactorInOverworld=3
}
```
I get the crash [here](https://gist.github.com/evhub/b61477c257c670256fdf63e71df727b2). This config certainly seems valid to me, though maybe I'm misinterpreting something.

**Comment by NotActuallyTerry** [comment]
Which version are you using? @evhub

**Comment by evhub** [comment]
@twrist 7.1.3.62

**Comment by Sunconure11** [comment]
Appears to be happening again, with vanilla settings.

https://pastebin.com/wpCizxpm

The kicker is that I'm trying to make a new world. On a server.

**Comment by Zygus42** [comment]
tropicraft-MC1.12.2-7.1.3.62
forge-1.12.2-14.23.3.2673-installer-win

Crash in  Tropicraft dimension:
[crash-2018-05-03_21.25.12-server.txt](https://github.com/Tropicraft/Tropicraft/files/1971035/crash-2018-05-03_21.25.12-server.txt)

Copy of config file:
[tropicraft.zip](https://github.com/Tropicraft/Tropicraft/files/1971034/tropicraft.zip)

**Comment by KollinsPlays** [comment]
It would help to change the config to a min size and a growth size or something where max size = min + growth, or maybe just a condition in the code that, when it sees max is less than min, spits out a warn in the log and then just sets max to what min is set to. It's kind of weird how the config file max value has a range in brackets that appears to change to match the min value but only after a session (or world?) loads. Maybe just state that this must be greater than what min is set to, but no more than 1001?

**Comment by TigerWalts** [comment]
Looking at this code, setting a min patch size below `2` will mean that there's a chance that the `spread` value is set a negative value:

- https://github.com/Tropicraft/Tropicraft/blob/7f4a5831c03a42440e3865c8fc3896bd4f3cb792/src/main/java/net/tropicraft/core/common/worldgen/WorldGenBamboo.java#L43-L49

If `amount` is calculated to be `1` then `(int)(Math.sqrt(amount) / 2)` evaluates to `0`.
This means that `int spread = rand.nextInt(3) - 1 + (int)(Math.sqrt(amount) / 2);` may evaluate to `-1`
This will cause line 49 to throw an Exception
