### ISSUE TITLE
palm trees doesn't spawn in overworld when option for they spawn only in beach is activated

### ISSUE THREAD

**Issue by 0Navis0** [Tropicraft/Tropicraft#269]
I think everything is in title.

**Comment by Broam** [comment]
Doing some testing of this issue (I wanted to put palm trees only on beaches in my private pack).
v 7.1.3.62
Config settings
genOverworldPalmsInBeachOnly: true
genTropicraftFlowersInOverworld: false
all other configs: default
Palm chance is -1

Created a world that is only Beach biome (Customize)

I'm seeing palm trees, unable to reproduce.

**Comment by comp500** [comment]
I have managed to reproduce this - they don't seem to appear in any generated Beach biomes, but they do generate if you make a world with only Beach biomes. It may be that the naturally generated Beach biomes are too small.

**Comment by tterrag1098** [comment]
Have you raised the chance value to accommodate for there being less valid spots to spawn?

**Comment by comp500** [comment]
The default chance value is -1, which means that they will always appear, however the code has a rand.nextInt(10) == 0 before checking the chance value.

**Comment by comp500** [comment]
I think I have found the issue, will make a PR shortly.

**Comment by comp500** [comment]
The reason for the issue being unreproducible in a Customized world is that the Beach biome is everywhere, so the `getBiome` call will always return a Beach biome, even though it is called with incorrect coordinates.

**Comment by Celks** [comment]
im having this problem. Its very difficult to find a palm tree in 1.12.2 or the bug didnt got fixed?
