### ISSUE TITLE
about lag in 1.12

### ISSUE THREAD

**Issue by forestbat** [Tropicraft/Tropicraft#273]
## Issue Description
The mod loaded many chunks and let the game slow，we need 2-3 minutes to enter a new world，and the log was written to over 100000 lines。

Tropicraft Version:   7.1.3.62
Forge Version:  14.23.3.2673

PASTE YOUR CRASH LOG HERE
https://gist.github.com/forestbat/e041c6dfd9b7a54621c646a19855b456

**Comment by tterrag1098** [comment]
Hi, please try with the latest version of forge, there have been some improvements made in this respect there.
