### ISSUE TITLE
(BUG) AutoWalk bug interaction between Tropicraft & Metamorph

### ISSUE THREAD

**Issue by Vaygrim** [Tropicraft/Tropicraft#276]
## Issue Description
Developing a pack that we would like to use Tropicraft in, and we ran across a fresh bug when trying it in combination with a mod called "Metamorph" (by Horsewithnoname). The issue we ran across is [weird](https://github.com/GrimCo/CoopLife2/issues/14).
Morphing from standard player form into any other form will cause you to get 'pulled' (or auto-walking as we call it) in a specific compass direction. Happens in Single Player, Multiplayer, Survival, Creative, Adventure mode.. everything. Chickens, Parrots, and Rabbits all get pulled SouthEast... while everything else gets pulled NorthWest. (No clue why this is.)

## Steps to Reproduce
1) Install Forge 2678+ , Metamorph 1.1.5 for 1.12.2, and Tropicraft 7.1.3.62
2) Log into a single player world and kill _anything_ to grab it's morph.
3) Change shape into that morph, you should immediately start getting pulled a specific compass direction.
   
Tropicraft Version:    7.1.3.62   
Forge Version:   2678 / 2680 (tried both)   

## Crash log
```
Not a crash-causing issue, just a weird interaction.
```

**Comment by NotActuallyTerry** [comment]
Might be fixed by 4947c1b, could you (or anyone else) please test if toggling that does fix it?
