### ISSUE TITLE
EIH still reacts to being hit in Peaceful

### ISSUE THREAD

**Issue by ayronce13** [Tropicraft/Tropicraft#279]
## Issue Description
Is there a way to prevent mob spawning or a config file I can edit for mob spawning? The frogs and stone heads keep spawning even when in peaceful.

## Steps to Reproduce
1)
2)
3)

Tropicraft Version:   1.12
Forge Version:   

## Crash log
```
PASTE YOUR CRASH LOG HERE
```

**Comment by twrist** [comment]
The entries you'll want to change in the config file are in the top within the `entity` block:

```java
entity {
    # Should Tropicraft's hostile land mobs spawn in the overworld?
    B:spawnHostileTropicsLandMobsOverworld=false

    # Should Tropicraft's hostile water mobs spawn in the overworld?
    B:spawnHostileTropicsOceanMobsOverworld=false

    # Should Tropicraft's passive land mobs spawn in the overworld?
    B:spawnPassiveTropicsLandMobsOverworld=false

    # Should Tropicraft's passive water mobs spawn in the overworld?
    B:spawnPassiveTropicsOceanMobsOverworld=false
}
```

In the future please use Discord for support requests like this, you're more likely to get an answer.

**Comment by twrist** [comment]
Nevermind, re-read the question.

**Comment by NotActuallyTerry** [comment]
There is currently no way to toggle their spawning behaviour in the tropics, however setting the difficulty to Peaceful disables their ability to inflict damage. The EIH's AI might need to be disabled though as that could get annoying.
