### ISSUE TITLE
Tropicraft and MFR Plastic Tank Crash

### ISSUE THREAD

**Issue by JAWSAWN** [Tropicraft/Tropicraft#28]
Launcher Crash Report:
http://paste.ubuntu.com/10822515/

Using Tropicraft v6.0.1
Latest MineFactoryReloaded and CoFH core installed.

1-Get a bucket of tropic water
2-Right click the tank with the bucket
3-Freeze and crash

**Comment by Cojomax99** [comment]
The Fluid IIcons were null, which caused this. This also, however, helped uncover an issue with MFR which I reported as an issue here: https://github.com/skyboy/MineFactoryReloaded/issues/433

This bug will be fixed in v6.0.3

**Comment by Adaptivity** [comment]
Confirmed to be fixed.
