### ISSUE TITLE
Fruit tree bug

### ISSUE THREAD

**Issue by SourKid2016** [Tropicraft/Tropicraft#280]
## Issue Description
When planting a (ex:orange) tree, it will mature as a (lime) tree, and vice versa (assumed). Said trees leaves read as the saplings corresponding leaves, but drop the trees fruit and saplings

## Steps to Reproduce
1)Plant fruit tree sapling (seen with orange)
2)wait
3)harvest lines
4)profit! But loose a lot of orange crop

Tropicraft Version:   6.0.5   (MC 1.7.10)
Forge Version:  10.13.4.1558      

## Crash log
```
PASTE YOUR CRASH LOG HERE
```

**Comment by NotActuallyTerry** [comment]
Closing as 1.7.10 is unsupported
