### ISSUE TITLE
Intermittent crashes after configuring bamboo spawn rates

### ISSUE THREAD

**Issue by KollinsPlays** [Tropicraft/Tropicraft#282]
## Issue Description
If a portal fails to appear when you get into the dimension, or you lose your portal while exploring, the ways to get back to the overworld are not available within the world. You can mine and make a Tropics Portal Enchanter Wand, but purified sand can't make sandstone to build the pool needed to use it.

## Steps to Reproduce
1) Drink in your chair in the overworld, to get to the dimension
2) game crashes or freezes when loading
3) when you get back into the game, you are in the dimension, but there is no portal to get back.

Tropicraft Version: 7.1.4.78   
Forge Version:   14.23.4.2702   

## Crash log
```
PASTE YOUR CRASH LOG HERE
```

**Comment by tterrag1098** [comment]
You said a crash is required to trigger this bug, where is the crash log?

**Comment by KollinsPlays** [comment]
I was thinking a crash is a different issue than not being able to make a portal from within the Tropicraft Dimension unless you brought outside resources. The issue I had was more that you can't craft or find sandstone within the dimension to use the portal wand.
That said, I was trying to narrow down why I was crashing and when I change the overworld spawn settings for bamboo ( I:maxBambooPerPatchOverworld=61 and I:minBambooPerPatchOverworld=2), drinking in a chair at sunset in a new world causes this crash:
https://paste.ee/p/N8Obh

**Comment by KollinsPlays** [comment]
I was able to load into the world after the above crash, but there was no return portal and after running around in the dimension a bit, when I walked back to the general area I had started in the dimension at, it crashed again.
https://paste.ee/p/Mh4rS

This part of the tropicraft .cfg and again, the only lines I changed from defaults were the bamboo overworld gen settings
    # Maximum amount of bamboo in a patch in the overworld [range: 3 ~ 1001, default: 120]
    I:maxBambooPerPatchOverworld=61
    # Maximum amount of bamboo in a patch in the tropics [range: 61 ~ 1001, default: 120]
    I:maxBambooPerPatchTropics=120
    # Minimum amount of bamboo in a patch in the overworld [range: 0 ~ 1000, default: 60]
    I:minBambooPerPatchOverworld=2
    # Minimum amount of bamboo in a patch in the tropics [range: 0 ~ 1000, default: 60]
    I:minBambooPerPatchTropics=60

**Comment by KollinsPlays** [comment]
I was attempting to change the Tropicraft config so that less of the mod's items are found in the Overworld to encourage travel into the Tropicraft dimension. The crashes I see have been narrowed down to changing the overworld bamboo generation values, which causes this crash when entering Tropicraft for the first time by drinking pina colada in a chair at sunset: https://paste.ee/p/Gz9cx

The ONLY settings I changed were in tropicraft.cfg for the above test/crash:
    # Maximum amount of bamboo in a patch in the overworld [range: 6 ~ 1001, default: 120]
    I:maxBambooPerPatchOverworld=59
    # Minimum amount of bamboo in a patch in the overworld [range: 0 ~ 1000, default: 60]
    I:minBambooPerPatchOverworld=5

With the above changes in place, the first loading of the dimension crashes and then loading the world up again, you are in the dimension, but no portal exists to get back and there are no resources in the dimension to create the sandstone needed to make a new portal.

This also causes random crashes while exploring the Tropicraft dimension: https://paste.ee/p/Q5aXt

**Comment by tterrag1098** [comment]
Can you repost those crash reports with permanent links?

**Comment by KollinsPlays** [comment]
I didn't realize the past.ee links were temporary, sorry.

I used a new template modpack that just has basic mods, added Tropicraft, launched it without making a world so it would create a config file, closed it, made the below changes, started a new world and drank a pina colada in a chair at sunset. The only changes I made were these 2 config options:
    # Maximum amount of bamboo in a patch in the overworld [range: 61 ~ 1001, default: 120]
    I:maxBambooPerPatchOverworld=59
    # Minimum amount of bamboo in a patch in the overworld [range: 0 ~ 1000, default: 60]
    I:minBambooPerPatchOverworld=5

And here is a permalink to the crash report:
https://pastebin.com/jgUXkCn9
