### ISSUE TITLE
Server crashes if player uses explosions on coconut

### ISSUE THREAD

**Issue by KaesBuerschtl** [Tropicraft/Tropicraft#284]
## Issue Description
When a player attempts to..."harvest" a coconut using an explosion (TNT, modded missiles, etc.) in a multiplayer environment (have not tested SSP), the server crashes.

## Steps to Reproduce
1) Locate coconut
2) Place TNT near coconut
3) Ignite TNT

Tropicraft Version:   tropicraft-MC1.12.2-7.1.4.78   
Forge Version:   forge-1.12.2-14.23.4.2707   

## Crash log
```
https://github.com/Tropicraft/Tropicraft/files/2103707/crash-2018-06-14_19.06.32-server.txt
```

**Comment by tterrag1098** [comment]
Tracking under #287
