### ISSUE TITLE
Sugar Cane deletes tiki torches

### ISSUE THREAD

**Issue by SciMuse** [Tropicraft/Tropicraft#285]
## Issue Description
i put half slabs to cover water for cane farm. every so often i put 2 half slabs to make full block. I put tiki torch on the two half slabs. it renders the 1 high torch. the cane is right next to torch. when cane grows to same height as torch, torch disappears. does not crash or anything.

Tropicraft Version:   7.1.4.78 
Forge Version:   2707

**Comment by tterrag1098** [comment]
Cannot reproduce, placing tiki torches on top of a double slab results in a normal 3-tall torch.
