### ISSUE TITLE
Steak thinks it's a Melon Slice?   Issues with Food :/

### ISSUE THREAD

**Issue by CSSwifty07** [Tropicraft/Tropicraft#288]
## Issue Description

The food is messed up, normally when you eat a steak you get 4 hunger replenished and your hunger is satisfied for quite a while. Well, after I went to the tropicraft realm for the first time in survival it was all messed up. Steak started to act more like a melon slice, it only replenished 1 hunger per and within a few seconds I would be hungry again. I do have other mods installed so I'm not sure if it's an issue with one of them but tropicraft definitely played a part in it and somehow triggered the issue. I don't have a crash log and I'm not really sure how it happened, anything else I can attach to help you guys figure it out and fix it?

## Steps to Reproduce
1) 
2)
3)

Tropicraft Version:   7.1.4.78   
Forge Version:   14.23.1.2601   

## Crash log
```
PASTE YOUR CRASH LOG HERE
```

**Comment by Kalmeira** [comment]
Do you have harvest craft installed? It changes food values unless you change the config.

**Comment by NotActuallyTerry** [comment]
Possible mod conflict, do you have a list of mods you were using? @CSSwifty07

**Comment by NotActuallyTerry** [comment]
Closing due to lack of reply and information.
