### ISSUE TITLE
1.7.10; Server loop error?

### ISSUE THREAD

**Issue by MysticKillerMC** [Tropicraft/Tropicraft#289]
## Issue Description
I have downloaded this mod, and opened the zip file to download both the actual mod, and the supporting mod. I believe it's an issue with the support, but after loading up, it gives me a message:

## Steps to Reproduce
1) Open zip folder and click mods, put into mod folder
2) Load up the launcher and click single player, (1.7.10) 
3) click world, and you should be sent back to the launcher with this message; The game crashed whilst exception in server tick loop
The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Exception in server tick loop

Tropicraft Version:   1.7.10   
Forge Version:   1.7.10   

## Crash log
The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Exception in server tick loop
```

**Comment by tterrag1098** [comment]
1.7.10 is receiving minimal support anyways, but there is little we can do without a full crash report.

**Comment by NotActuallyTerry** [comment]
Closing due to both Outdated and lack of crash log
