### ISSUE TITLE
tropicraft idea

### ISSUE THREAD

**Issue by lukasXD1** [Tropicraft/Tropicraft#29]
Hello I have a few ideas and improvements 1.more animals (tiger, parrot, dolphin and shark) 2. Then the boot in the underwater perhaps rin few small treasures are 
3.survive is not big challenge,so maybe more monster or my idea search strains the hunt xour in the night (ec. ,,the forest")
4.more farming plants and ores
5.and more dungeos :D
I'm a big fan from tropicraft 
Keep it up and sorry for my bad english , i dont can good english

**Comment by JAWSAWN** [comment]
I think that Tropicraft has that big Peace aspect. (come on even creepers explode into flowers!) So I have to disagree with the more challenging survival (aren't frogs annoying enough?)
But I agree with the more dungeons! Adventure is always been fun! You should give them a little bit time though.

**Comment by Cojomax99** [comment]
Thanks for the suggestions! We will look into adding more adventures. In the meantime, we are added many new mobs in upcoming releases, including dolphins and sharks in the 1.10.2 release :) Enjoy!
