### ISSUE TITLE
Crash on Seaweed Placement (1.12.2) (Client)

### ISSUE THREAD

**Issue by TheGameAce** [Tropicraft/Tropicraft#291]
Here's the log, courtesy of Vanilla Fix. Don't recall specific forge version offhand, sorry.
https://paste.dimdev.org/agisevujol.mccrash

Placed seaweed for a tank and immediately got a client crash. Still placed the seaweed upon rejoining at least, so I guess it's worth repeated crashes for the sake of a perfect fish tank?
Seaweed also is treated more like an entity rather than a block it would seem, can only be placed on foamy sand, and can only be removed by breaking the block under it. Not sure if that's intentional or an error.
Another thing to note here is that after the crash Seaweed appears to place normally, although only a block high and that cannot be changed it would seem. Previously when it crashed, the seaweed was put to the maximum height of the water at the time.

Also a few other things I've noticed - Palm Saplings don't appear to drop from Palm Tree leaves (nor do the leaves decay naturally). Starfish don't appear to spawn naturally. Purified Sand isn't affected by shovels like normal sand (diamond shovel does the same mining speed as by hand). Shaka Stone gives off experience when mined without giving any sort of an ore or anything. Due to this, you can make an experience loop by placing down large quantities and mining it repeatedly.
Appears that fish also still get stuck on blocks when they swim into them.

**Comment by tterrag1098** [comment]
Should have been fixed by 6aecb138fc9e2696bcd5e1928c793b42fbc977ad
