### ISSUE TITLE
Possible world corrupting error involving Tropicraft

### ISSUE THREAD

**Issue by Sunconure11** [Tropicraft/Tropicraft#293]
## Issue Description

User of my modpack reported a possible crash involving Tropicraft. Not sure how he triggered it, but it ended up corrupting his world.

## Steps to Reproduce
1) ???
2) ???
3) Crash

Tropicraft Version:  7.1.4.78
Forge Version:  14.23.4.2760

## Crash log
https://paste.dimdev.org/livitufewu.mccrash

**Comment by tterrag1098** [comment]
This isn't world corruption, some other mod is adding biomes to our world generator...which is not expected.

**Comment by Sunconure11** [comment]
Strange.

**Comment by NotActuallyTerry** [comment]
Do you still have a copy of that modpack? @Sunconure11

**Comment by Sunconure11** [comment]
Yes, but Tropicraft has since been pulled from the pack.

**Comment by bs2609** [comment]
Will link https://github.com/MinecraftForge/MinecraftForge/pull/5720 as possibly related to this issue.
