### ISSUE TITLE
 Newest Mod Update to Tropicraft have a sit bug

### ISSUE THREAD

**Issue by Titoo8899** [Tropicraft/Tropicraft#295]
On your newest mod is all of the thinks very good with the design only one think.
Then I will sit it is 180 grad on the wrong right, I have 2 Pictures who you can see it easy what I mean.
![2018-11-04_11 27 11](https://user-images.githubusercontent.com/42325138/47963072-e6c74c00-e026-11e8-95b3-da18b3817a6c.png)
![2018-11-04_11 27 24](https://user-images.githubusercontent.com/42325138/47963073-e6c74c00-e026-11e8-9890-8f3fbaec9f8c.png)

**Comment by Titoo8899** [comment]
The first Picture you can see I sit not right. Please fix this Problem and the other picture show how I sit on this seeflote or what the name of this item was. I sit under the water please fix this 🗡

**Comment by tterrag1098** [comment]
Have you tried without mo' bends installed?
