### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Mgazul** [Tropicraft/Tropicraft#296]
## Issue Description
ERROR

## Steps to Reproduce
1)
2)
3)

Tropicraft Version:    tropicraft-MC1.12.2-7.1.5.85
Forge Version:   14.23.5.2772

## Crash log
[Gist](https://gist.github.com/twrist/ca1ea080c2d52a6189446914d0ba8e89)
```

**Comment by NotActuallyTerry** [comment]
Do you have the latest.log for this crash?

**Comment by Mgazul** [comment]
No crash. This error occurs when the server is first started or after the player enters the server.

**Comment by tterrag1098** [comment]
Ignore that, that commit won't fix this.

**Comment by tterrag1098** [comment]
Anyways, this does not seem related to Tropicraft. It helped me find an unrelated bug, but we do not control when netty's ByteBufs are released. This sounds like a forge or even netty bug, way beyond what we control. It's probably safe to ignore.

**Comment by Mgazul** [comment]
thank! I will check my own problems!

**Comment by bs2609** [comment]
You're leaking the buffer here:
https://github.com/Tropicraft/Tropicraft/blob/93f30443b3b55d1e651e6d0739091ce1d6868e14/src/main/java/net/tropicraft/core/common/network/MessagePlayerSwimData.java#L30

`buf.readBytes(len)` creates a *new* buffer, see the [Javadoc](https://netty.io/4.1/api/io/netty/buffer/ByteBuf.html#readBytes-int-).

**Comment by tterrag1098** [comment]
Thanks, this should be actually resolved now.

**Comment by Mgazul** [comment]
Yes, the problem has been solved
