### ISSUE TITLE
[Suggestion] Coffee needs to be added to Ore Dictionary

### ISSUE THREAD

**Issue by DWX12** [Tropicraft/Tropicraft#302]
## Issue Description
Coffee needs to be added to Ore Dictionary

## Steps to Reproduce
None

Tropicraft Version:7.1.8.105   
Forge Version: NA

**Comment by tterrag1098** [comment]
Can you be more specific? Why does it need to be added? To what name?

**Comment by DWX12** [comment]
Sorry I haven't replied back sooner. Last time I checked, Tropicraft coffee wasn't compatible with mods such as CoffeeWorkshop, Pam's Harvestcraft, and many others. I don't know if anything has been changed since then though.
