### ISSUE TITLE
Player size is forcibly set, interfering with AoV

### ISSUE THREAD

**Issue by Jackiecrazy** [Tropicraft/Tropicraft#307]
## Issue Description
AoV has a polymorph skill to transform into a wolf (1 block height). I don't exactly know what the cause of this is (perhaps scuba gear?), but when both are installed together the player's height will not be modified in wolf form.

EDIT: found it in scubahandlercommon, will also pester Tamaized to move size restrictions later down the line.

## Steps to Reproduce
1) Install AoV and Tropicraft
2) /aov setlevel 15, get wild form-wolf from druid statue
3) transform

Tropicraft Version:   7.1.8.105
Forge Version:   shouldn't affect anything, but 2796

**Comment by tterrag1098** [comment]
The code is a bit foreign to me, and fragile, so instead I just added a config to disable the animation: https://github.com/Tropicraft/Tropicraft/commit/4947c1b05b6b8438e7f31dcd557c332262269c42

It's not a real fix, but it will solve the problem.

**Comment by Jackiecrazy** [comment]
It got fixed on the other side too, thanks for looking into it!
