### ISSUE TITLE
Re-add volleyball?

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [Tropicraft/Tropicraft#31]
I think it would really fit with the theme of the mod if the volleyball stuff could be re-added.
At least a net should be, because then you could use the Sports mod for the ball.
I'd love to see volleyball implemented again because I have a couple of characters on my game who like volleyball as a hobby. Plus, they are both from Anguilla, which is a Caribbean island, so I put their houses in the Tropics dimension. I could make the textures if you want me to, because I'm pretty good at making skins for Minecraft mobs and whatnot.

**Comment by Cojomax99** [comment]
Volleyball was never completed, so I would have to finish it before adding it back in. But if I have time, I will think about it.

**Comment by AGiLE-EaGLE1994** [comment]
Thank you. C: I appreciate you taking my feedback into account :D

**Comment by Cojomax99** [comment]
Added it to the backlog...we'll see where it goes :)
