### ISSUE TITLE
Compatibility issues with Multi Mob Library 

### ISSUE THREAD

**Issue by groovysmooth** [Tropicraft/Tropicraft#310]
## Issue Description

When this mod is used alongside anything requiring Multi Mob Library, many corrupted entities in the form of white polygons LITTER the Tropics dimension, alongside an array of mobs that should not be spawning there.

Developer of Multi Mob has looked into this issue (as it has been brought to his/her attention by others, not just me), and has confirmed that this is an issue on Tropicraft's end.

## Steps to Reproduce
1) Install Multi Mob Library, and a dependent (reproduced on my end with Primitive Mobs)
2) Load up tropics dimension.
3) Behold the corrupted entity spawn.

Tropicraft Version:   7.1.8.105   
Forge Version:   1.12.2 - 14.23.5.2823   

## Crash log
```
no crashes
```

**Comment by tterrag1098** [comment]
Where did they confirm this? It would be very helpful to know what exactly they think is wrong to be able to fix it.

**Comment by groovysmooth** [comment]
Sorry I should have included that from the beginning! The dev was responding to a comment on the Multi Mob Library page on CurseForge...

"So I just checked and this seems like something on Tropicraft's end. They should take the result of the CheckSpawn event into consideration for their spawn system so my mobs do their proper checks. Now everything just spawns willy nilly."

And here is the link if you want to read the whole thread.

https://minecraft.curseforge.com/projects/multi-mob-core?gameCategorySlug=mc-mods&projectID=309136

(Comment in question is https://minecraft.curseforge.com/projects/multi-mob-core?comment=51 ~@twrist)

Thanks for your swift reply!

**Comment by RhapsodySL** [comment]
Bumping this issue up; this is unfortunately still occurring.

**Comment by Vectrobe** [comment]
What specific requirement is needed from the CheckSpawn event? current behaviour is vanilla-esc, mobs are only registered to spawn in their select biomes (including config options).

**Comment by SlashClaw14** [comment]
This issue still persists and I couldn't find a work around. Hopefully a fix is still on the way (the CurseForge page hasn't had a new build in almost a year)
