### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Boymann** [Tropicraft/Tropicraft#311]
## Issue Description
I have a lot of mods, so I'm not sure what conflict could be causing it. I'm just pasting a crash log, trying to help maybe.

## Steps to Reproduce
1)Start minecraft.
2)?
3)Crash

Tropicraft Version: tropicraft-MC1.12.2-7.1.8.105
Forge Version:  2835

## Crash log
[latest.log](https://github.com/Tropicraft/Tropicraft/files/3141450/latest.log)

**Comment by TrueDragonHeart** [comment]
Well it could be you have too many dimension mods, i had the same problem and had to sift through but its just a guess.

**Comment by Boymann** [comment]
The amount of mods have not changed before and after the crash, I just updated some mods, if I recall correctly.

**Comment by NotActuallyTerry** [comment]
@Boymann Can you please retry this with v7.1.9?

**Comment by Boymann** [comment]
Seems fixed, no crash on startup, nor world creation.
