### ISSUE TITLE
Thatch lighting glitch

### ISSUE THREAD

**Issue by Blazer4Hire** [Tropicraft/Tropicraft#312]
There is a lighting problem that causes blocks like thatch roof to get glitched shadows.

1) Place thatch roof not touching blocks.
2) Place a full block touching it.

Tropicraft Version:   7.1.8.105   
Forge Version:   14.23.5.2836

**Comment by tterrag1098** [comment]
Do you have a picture of the issue?

**Comment by Blazer4Hire** [comment]
Sorry I didn't send this earlier, by the time I got the message it was like 12 at night for me. If I get any more bugs like this again I will remember to send a screenshot just in case it cannot be reproduced.
![2019-05-21_09 00 05](https://user-images.githubusercontent.com/50091501/58098164-f5321b00-7ba6-11e9-934b-448afb1013d2.png)

**Comment by NotActuallyTerry** [comment]
I cannot reproduce this bug with the same or similar layout to the one in the picture. What are your graphical settings set to? Are you using any graphical enhancement mods?

**Comment by tterrag1098** [comment]
Are you using Optifine?

**Comment by Blazer4Hire** [comment]
*facepalms* Yes, yes I am, that was probably it. I tried to use the pack without optifine and it keeps crashing. I completely forgot I had optifine, that is probably what it was because it sometimes can cause lighting problems. Sorry to bother you.
