### ISSUE TITLE
Unknown mod messing with Tropicraft worldgen

### ISSUE THREAD

**Issue by BugmanBugman** [Tropicraft/Tropicraft#314]
## Issue Description
game crashes after entering tropicraft for the first time, cites vanilla biome incompatibility.
## Steps to Reproduce
1) drink colada
2)enter the dimension
3)game freezes up, then crashes

Tropicraft Version:   Tropicraft - 7.1.9.115   
Forge Version:   14.23.5.2838   

## Crash log
https://paste.dimdev.org/kezezebepi.mccrash

https://paste.dimdev.org/axazocukew.mccrash

**Comment by tterrag1098** [comment]
This is caused by another mod messing with our worldgen.

**Comment by NotActuallyTerry** [comment]
Same issue as #275, I'd suggest comparing your mod lists and seeing what you have in common to help narrow it down.

**Comment by Vectrobe** [comment]
try without aether_legacy, you'll also need to purge the tropi DIM to reset the biomes, as forge will default to random vanilla biomes when mod ones are removed, causing the crashes relating to vanilla biomes.

**Comment by Vectrobe** [comment]
the crash itself is fixable, however the result will still be a corrupt DIM, which requires either a purge of the DIM or the broken region files, or manual correction with the likes of mcedit or worldedit
