### ISSUE TITLE
Crash when overworld bamboo spawn rate is edited

### ISSUE THREAD

**Issue by viceroy369** [Tropicraft/Tropicraft#315]
If I try to edit the overworld bamboo spawn rate in tropicraft's config I constantly get this crash in the tropicraft dimension (overworld is fine)

https://paste.dimdev.org/xenaqugehu.mccrash

This crash does not seem to occur with bamboo spawn rates at the default.

Tropicraft 1.12.2 version 7.1.9.115
Forge 14.23.5.2836

**Comment by tterrag1098** [comment]
To what exactly did you change them to?

**Comment by viceroy369** [comment]
Can't remember exactly but it was definitely within the allowed values given in the config file.

**Comment by Vectrobe** [comment]
It's a combined narrowness that causes the spread to zero-out given enough chance.
