### ISSUE TITLE
[1.12.2] Client crash when using portal enchanter.

### ISSUE THREAD

**Issue by ProsperCraft** [Tropicraft/Tropicraft#320]
## Issue Description
Client crash with the creation of a portal using the portal wand.

## Steps to Reproduce
1)Click on a sandstone square, even it is already a portal.

Tropicraft Version:   tropicraft-MC1.12.2-7.1.9.115
Forge Version:   2838

## Crash log
```
https://gist.github.com/ProsperCraft/040a44d32bde1f914f1b3fa9edb93b9c
Reproduced here - 
https://paste.dimdev.org/elutubaxip.mccrash
```

**Comment by NotActuallyTerry** [comment]
I'm having some difficulty reproducing this, was it in the overworld or the tropics?
If possible, could you send the savefile over to me?

**Comment by ProsperCraft** [comment]
First one was in the tropics, second was in the overworld.

This was on my multiplayer server - try with my modpack - 

[https://minecraft.curseforge.com/projects/drtardis-2-new-adventures/](https://minecraft.curseforge.com/projects/drtardis-2-new-adventures/)

Several of us are living in the tropics because it is much safer.

**Comment by NotActuallyTerry** [comment]
This bug only happens on Multiplayer servers
Steps to re-create:
1) Host a Minecraft server with Forge + Tropicraft installed, and connect to it
2) Give yourself a Tropics Portal Enchanter
3) Create a new portal with it
4) Right-click on the portal's sandstone with the wand

**Comment by Vectrobe** [comment]
The wand is attempting to spawn a portal on the client, and due to the server being remote, the local server doesn't exist and thus the client nullptr's.
