### ISSUE TITLE
Hostile sea mobs are passive.  aka- punch a shark in the nose.

### ISSUE THREAD

**Issue by ProsperCraft** [Tropicraft/Tropicraft#321]
## Issue Description
you can swim and harm hostile sea life like sharks and they don't react.

Tropicraft Version:   tropicraft-MC1.12.2-7.1.9.115   
Forge Version:   2838

**Comment by Vectrobe** [comment]
What difficulty mode?

**Comment by ProsperCraft** [comment]
difficulty=2

**Comment by Vectrobe** [comment]
got a mod list?

**Comment by ProsperCraft** [comment]
https://www.curseforge.com/minecraft/modpacks/drtardis-2-new-adventures

**Comment by Vectrobe** [comment]
try without vanillaFix?
