### ISSUE TITLE
No mobs spawn in tropic world when CustomMobSpawner installed

### ISSUE THREAD

**Issue by ztllllll** [Tropicraft/Tropicraft#325]
If CustomMobSpawner is in the mod folder,it will cause no animal or enemy spawn in tropic world.after some test, l have found delete CustomMobSpawner then tropic mobs will spawn normally.

Tropicraft Version:   tropicraft-MC1.12.2-7.1.9.115
Forge Version:   1.12.2-forge1.12.2-14.23.5.2838
CustomMobSpawne Version:   1.12.2-3.11.4

**Comment by tterrag1098** [comment]
Duplicate of #222
