### ISSUE TITLE
Aquatic creatures not spawning

### ISSUE THREAD

**Issue by captincanada** [Tropicraft/Tropicraft#326]
I stepped into the Tropicraft realm on my modded world and I found no mobs, zero, spawning in the water.
I searched around the world for a bit and swam underwater but I found no fish spawning. Other creatures such as Monkeys, Iguanas, frogs, parrots, etc. spawn on land in a proper manner but I couldn't find any sea creatures.

Tropicraft Version:   1.12.2 / 7.1.9.115
Forge Version:   1.12.2-14.23.5.2838

**Comment by tterrag1098** [comment]
Do you have any other mods installed, particularly any that impact mob spawning?
