### ISSUE TITLE
animals spawning indoors

### ISSUE THREAD

**Issue by ramirez223** [Tropicraft/Tropicraft#327]
## Issue Description
iguanas, frogs, tropicreepers and heads spawning in basement/building thats sealed off  

## Steps to Reproduce   
1)build 47x31x10 room ( LxWxH)   
2) light it up   
3) walk around   
4) result: [https://imgur.com/a/mFcJvJp](url) (note: hole in wall in pic has door on it)   
Tropicraft Version: 7.1.9.115   
Forge Version:  1.12.2-14.23.5.2813

**Comment by mcdodge34** [comment]
Will this bug ever be fixed, just curious here, was planning a build in Tropicraft dimension but if I can't even be safe inside, I'm getting out
