### ISSUE TITLE
Incompatible with Dooglamoo worlds

### ISSUE THREAD

**Issue by ZephaniahNoah** [Tropicraft/Tropicraft#329]
When I create a new world the game crashes. I don't know which mod is at fault. It may not even be an issue within Tropicraft.
[crash-2019-09-18_12.43.25-server.txt](https://github.com/user-attachments/files/22181608/crash-2019-09-18_12.43.25-server.txt)

**Comment by Dooglamoo** [comment]
This has been fixed in the newest version of Dooglamoo Worlds.
