### ISSUE TITLE
Cocktail umbrella missing texture and portal problems

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [Tropicraft/Tropicraft#33]
The texture on the umbrella in the caipirinha is missing.
Plus, I have problems going to and from the Tropics realm, and I'm not sure why, but sometimes (Most of the time) the portal just doesn't work, and neither does using the chair at sunset. D:
So I just use the /tropics command instead.
Cojo, can you fix this?

**Comment by Cojomax99** [comment]
http://i.imgur.com/ZoUtVk4.png :D

**Comment by Cojomax99** [comment]
Please re-file another bug for the teleport issue if it is still a problem in v6.0.4.

**Comment by AGiLE-EaGLE1994** [comment]
Thanks. C:
