### ISSUE TITLE
Personal Bug List

### ISSUE THREAD

**Issue by partyloveus101** [Tropicraft/Tropicraft#34]
I'm personally a big fan of tropicraft so it was great to see the new version so I just wanted to post issues I noticed. 

Cannot find any pineapples - I had looked everywhere and was unable to find any of them so I then just used too many items to get the pineapple chunks. 

Cannot create the chair - I got all of the items together and tried to create the item but it just wouldn't work even with colored wool's. 

The tropical world didn't fully load - The world seemed quite empty so I started to travel around and then it just stopped at a dead end. 

I went to the tropical world again and I noticed there were no fish or coral 

Because the world wasn't fully their I couldn't find more bugs but if I do I will continue to post them.

**Comment by Cojomax99** [comment]
I have fixed most of these. Some were addressed in #25.
