### ISSUE TITLE
Grass spawning in the nether

### ISSUE THREAD

**Issue by pyrossal** [Tropicraft/Tropicraft#360]
## Issue Description
Grass is spawning in the nether. I dont know why but apparently its bacause of this mod

## Steps to Reproduce
1)
2)
3)

Tropicraft Version: idk  
Forge Version:   1.12.2
![image](https://user-images.githubusercontent.com/63841160/79543598-78bafb80-80d9-11ea-940f-9c444237a79e.png)
![image](https://user-images.githubusercontent.com/63841160/79543672-96886080-80d9-11ea-820a-4ea2149de16d.png)

**Comment by tterrag1098** [comment]
This must be caused by some other mod, it does not occur with only Tropicraft installed.
