### ISSUE TITLE
Excess network packets

### ISSUE THREAD

**Issue by ghost** [Tropicraft/Tropicraft#364]
Upon noticing excessive Client->Server traffic I stuck redshark in and found the following being sent a lot:
[Taken from server side]
Recieved a packet from Tropicraft. It has 97 bytes of data. Type is class net.tropicraft.core.common.network.MessagePlayerSwimData.

May be related to #296 in some way.

Tropicraft: 7.1.9.115
Forge: x.2854 (1.12)

This is creating a data stream from 15-30KB/sec Client to Server and about the same in the other direction (these packets show up as going both directions with the same size). The rate seems to vary depending on where I'm at.

And I'm in the overworld at spawn and am the only one on.

**Comment by tterrag1098** [comment]
Yes, the swim animation stuff is quite network intensive. If it's too much for your server, I suggest disabling the feature.

**Comment by ghost** [comment]
Oh, I didn't realize there was an option, thanks for letting me know, I'll take a look at disabling that.

That said, why would it be doing it if I'm on dry land or flying in the air? The traffic is basically constant save for when I teleport or change dimensions, doesn't matter what I'm doing or not doing.

**Comment by tterrag1098** [comment]
Probably just missing some checks, I can maybe look into it at some point but 1.12 isn't a priority right now.
