### ISSUE TITLE
Implement a way to remove the tropicraft dimension portal

### ISSUE THREAD

**Issue by jacobholden** [Tropicraft/Tropicraft#368]
I have a suggestion, implement a way to remove the tropicraft dimension portal. Make a new craftable drink, that when drunk and the player enters the portal, the portal blocks become removable and the portal becomes inactive.

**Comment by Dragon-Seeker** [comment]
Really what should be done is to check if the portal is still intact somehow similar to the nether portal and then disconnect it from there. There is no need to have another item to destroy a portal rather than smarter portal code for detecting a proper portal

**Comment by NotActuallyTerry** [comment]
Issue folded into #435, please follow updates from either there or #430
