### ISSUE TITLE
Dive computer looks like a vanilla map

### ISSUE THREAD

**Issue by darthvader45** [Tropicraft/Tropicraft#370]
## Issue Description
For some reason when holding the dive computer in my hand it looks like a map.

## Steps to Reproduce
1) Craft dive computer (5 chunk o head and one azurite if I remember correctly)
2) Hold it in your hand.
3) See the vanilla map texture in your hand and be disappointed.

Tropicraft Version:    7.1.9.115   
Forge Version:  14.23.5.2854

**Comment by tterrag1098** [comment]
That is...unfortunately intended. It was supposed to get some more custom rendering but it never happened. Not that there's much lost, you can see all the info on your HUD.

**Comment by darthvader45** [comment]
Huh, didn't see anything on there.  Normally I'd expect to see stuff like my depth, air, etc.

**Comment by tterrag1098** [comment]
Hm, try putting on goggles, it might be tied to that.

**Comment by darthvader45** [comment]
Yep, still nothing.  Not sure if In-Game Info XML might be conflicting, or other HUD mods.

**Comment by tterrag1098** [comment]
It should definitely render something if you're wearing goggles.

**Comment by darthvader45** [comment]
![image](https://user-images.githubusercontent.com/2816420/92298052-24db7280-ef13-11ea-9758-d3067636f2ae.png)
Here's a screenshot, holding the dive computer and wearing the scuba goggles.

![image](https://user-images.githubusercontent.com/2816420/92298073-48062200-ef13-11ea-98ba-9222d84233d8.png)
Ditto, underwater.
