### ISSUE TITLE
Modded swords can't break pineapples/coconuts into chunks.

### ISSUE THREAD

**Issue by Mysteriaa** [Tropicraft/Tropicraft#374]
## Issue Description
Basically the title. Breaking a coconut or a pineapple with a modded sword doesn't result in chunks being received, requiring the use of a vanilla sword (wood, etc).

## Steps to Reproduce
1)   Grow pineapple and/or coconut.
2)   Break pineapple/coconut with any sword not from the base game.
3)   Receive no chunks from either item. Revel in disappointment.

Tropicraft Version:   8.1.0-beta+34 (for MC 1.15.2).
Forge Version:   31.2.41

**Comment by NotActuallyTerry** [comment]
Confirmed in 1.15 using Tetra and 1.16 using Tinker's Construct
