### ISSUE TITLE
1.15 crash on launch

### ISSUE THREAD

**Issue by Tyrius1** [Tropicraft/Tropicraft#376]
## Issue Description
Crash on launch

## Steps to Reproduce
1)Launch game before drinking morning coffee
2)no real steps to reproduce
3)doesn't happen every time maybe 1/5 - 1/10 ?

Tropicraft Version:   8.1.0-beta+34   
Forge Version:   forge-31.2.41   

## Crash log
```
PASTE YOUR CRASH LOG HERE
https://pastebin.com/gVVPbRsy

**Comment by Tyrius1** [comment]
finally happened again. here's the latest log:
https://pastebin.com/gk1dix9W
and the new crash report:
https://pastebin.com/GuK2MbZY

**Comment by tterrag1098** [comment]
> EmbellishCraft: if this line crashes please report to https://github.com/MapperTV/embellishcraft/issues/19

This isn't a tropicraft crash.
