### ISSUE TITLE
(1.15.2) Tropicraft Portal doesn't spawn

### ISSUE THREAD

**Issue by Purplo262** [Tropicraft/Tropicraft#377]
I was testing out the mod on a 1.15.2 Modpack and noticed the portal never spawned. This was on both ends, I tried once from the overworld to the tropical realm, and again from the tropical realm back to the overworld. Both times a portal did not spawn, I simply 'teleported' into the other dimension. 

Steps to Reproduce
1)Place Chair and Umberella, drink Pina Colada at sunset
2)Teleport into other dimension, expect portal to have spawned
3)There is no portal

Tropicraft Version:   Tropicraft 8.1.0 beta 34.  
Forge Version:   31.2.21.  

No crash log, but here is the latest log: https://pastebin.pl/view/9358408d

**Comment by NotActuallyTerry** [comment]
Hey there!

Unfortunately this is intended, as we didn't have time to port the portal code for 1.15.
Hopefully though you'll see the return of the ~~in~~famous Tropicraft Portal soon!
