### ISSUE TITLE
Entity loot drops appear not to happen after 1.12

### ISSUE THREAD

**Issue by ramou** [Tropicraft/Tropicraft#379]
## Issue Description
When killing mobs in Tropicraft, loot isn't droping.

## Steps to Reproduce
1) Kill an Iguana
2) Notice no drops
3) Use console commands to give Iguana Leather to make Scuba Harness

Tropicraft Version:   8.1.0
Forge Version:   all versions

## Crash log
No Crash

## Suggested fix
As the goal is to move away from hardcoding drops in the entity files, look into creating the appropriate loot drops via the more modern mechanism that would deliver the same drops as the 1.12 hardcoded `dropLoot` and/or `dropSpecialtems` would.

**Comment by Gegy** [comment]
This is resolved as of https://github.com/Tropicraft/Tropicraft/commit/21cbd80413c5f1f78d53f34bfc166f2ec3bb8aba. 😊
