### ISSUE TITLE
Tropicraft event subscriber overworking with InControl custom mob spawns

### ISSUE THREAD

**Issue by zediious** [Tropicraft/Tropicraft#389]
## Issue Description

With the modpack I am creating, I am distributing parasites from the "Scape and Run Parasites" mod throughout various dimensions/planets, Tropicraft being one among Atum, Earth, The Nether, and a few custom JED defined dimensions. These dimensions do not go above roughly 15-25ms tick time when these "battles" are occurring

Using the same settings for mob spawning as these other planets, and visually seeing the same amount, Tropicraft's Event Subscriber for the server tick starts to create huge amounts of lag, bringing the TPS down to roughly 9 on my system. I am using InControl to spawn the Koa villagers throughout the dimension rather than just at their villages.

My question is, do the Koa Villagers have some functions attached to them that would be constantly trying to fire if they're in a different place or doing different things than normal?

## Steps to Reproduce
1) Download the SR Parasites mod, InControl, and Tropicraft (Atum if you would like to cross-reference)
2) Add the following InControl json files to the `InControl` folder in config.
    - https://gist.github.com/zediious/0adc6e46c250c1949ea871077addc093
    - https://gist.github.com/zediious/415fe99d804a6dafc44c271bacce319a
3) Visit Tropicraft and Atum, see the mob amounts and compare TPS.

Tropicraft Version:   **7.1.9.115**   
Forge Version:  **14.23.5.2855**    

## Crash log

No crash log, have an image of a LagGoggles profiler showing the Tropicraft server tick subscriber being bloated
I will gladly provide any more information you may need, I would love to have the Koa villagers spawning as such.

![Screenshot_34](https://user-images.githubusercontent.com/12464778/120942914-e40ac700-c6f9-11eb-9e66-64e8d74f1585.png)

**Comment by NotActuallyTerry** [comment]
They do have functions which attach them to their villages, but whether they'd go into ***HYPERSPEED*** would be something that @Corosauce would be able to answer

**Comment by zediious** [comment]
> 
> 
> They do have functions which attach them to their villages, but whether they'd go into _**HYPERSPEED**_ would be something that @Corosauce would be able to answer

Awesome :) It's certainly possible for me to use some other type of mob as the "fighting the parasite" mob if it's not something that can be resolved, the Koa just fit the best.

**Comment by NotActuallyTerry** [comment]
Upon discussions, I would highly suggest using a different mob for that. There was quite a bit of work done to force Koa to spawn & live in their villages. To fix this issue, we'd have to do an extensive amount of mob behaviour rewriting, which we're not particularly willing to do. If somebody else would like to take a crack at it and submit a PR though, we'd happily accept! Sorry about that

**Comment by zediious** [comment]
Thank you for the resolution! Makes perfect sense. We did find quite a few suitable mobs to use :)
