### ISSUE TITLE
"Errors in currently selected datapacks prevented world from loading"

### ISSUE THREAD

**Issue by SkipSnap** [Tropicraft/Tropicraft#394]
##Description
Hello, I just had an issue trying to play tropicraft in a set of mods I made. I had a problem where every time I generated a world, it would give the above errror message and give me the option to either play in “safe mode” or go back to title screen. I traced this problem to tropicraft, as the modpack works just fine without it in the folder.

## Steps to Reproduce
1) open pasted mods folder
2) add Tropicraft 1.16.5
3) generate a world

Tropicraft Version:   
Forge Version:   

## Crash log
```
PASTE YOUR CRASH LOG HERE
```

**Comment by Gegy** [comment]
Hi! Would you be able to share the log file from when this error happened? Should be in `<minecraft directory>/logs/latest.log` after running the game and getting this error 🙂 
Thanks!

**Comment by SkipSnap** [comment]
Yes of course
[latest.log](https://github.com/Tropicraft/Tropicraft/files/6702751/latest.log)

Im running 36.1.23 forge version and 9.0.0 beta 54 for the Tropicraft version

**Comment by SkipSnap** [comment]
Shoot sorry didnt mean to do that!

**Comment by Gegy** [comment]
This should be fixed now- if you can test with the build that should be shortly uploaded [here](https://github.com/Tropicraft/Tropicraft/runs/2896212400), that would be wonderful!

**Comment by SkipSnap** [comment]
I just downloaded an artifact.zip file from the link that was sent, is that the changes that were added or smth? sorry, Im asking stupid questions

**Comment by Gegy** [comment]
They're not stupid questions at all! The artifact.zip is a zip file that contains a new version of the mod with the fix applied 🙂 
Alternatively, just realised you can skip the zip and download the jar [here](https://ci.tterrag.com/job/Tropicraft-1.15/56/artifact/build/libs/Tropicraft-9.0.0-beta+56.jar) and just put that directly into your mods folder. If you can't get it working, dw! We'll release the fixed build soon too. :D

**Comment by SkipSnap** [comment]
Alright, well it’s working! Thank you very much for your patience!
