### ISSUE TITLE
Tropicraft Ideas

### ISSUE THREAD

**Issue by badboysuper** [Tropicraft/Tropicraft#4]
Some ideas/add some:
-sharks to coralreefs
-Different tropicforest trees
-more natural looking vulkanos
-lava slinger boss dropping a vulkano wand
-vulkano wand can activate vulkano's and stop them/removes lava to water
Hard to make(-add tides/foods where every water goes 1-5blocks higher)
-Tropicmaschienes (wind counter....)
-Storms like they can move blocks

Yeah i love this mod and remember just ideas

**Comment by Cojomax99** [comment]
Ideas have been noted. Thanks for the suggestions! :)

**Comment by badboysuper** [comment]
Oh my god! I just received an Email notification to this and it is amazing that you are continuing my favourite mod!!! I havent played minecraft in a while, but if this gets an cool update I will definetly start on a new world with a friend... Do you need more Ideas? I have more recent ones ;D

**Comment by Cojomax99** [comment]
I'll never turn down an idea :)
