### ISSUE TITLE
Minecraft crashed when koa villager's leaf ball hit a Minecraft Comes Alive's villager

### ISSUE THREAD

**Issue by abidoang** [Tropicraft/Tropicraft#40]
So I was testing koa villagers in a normal village full of MCA Villager. They start throwing leaf balls at me because I hit them. When one of the leaf ball hit an MCA villagers, my world crashed. Here's the crash report: http://pastebin.com/rTr7D52e

**Comment by Corosauce** [comment]
Looks like an issue on MCA's side, hard to confirm without looking at their code.

**Comment by Cojomax99** [comment]
Outdated, closing.
