### ISSUE TITLE
textures not showing up

### ISSUE THREAD

**Issue by 901327** [Tropicraft/Tropicraft#41]
I recently installed the latest version of tropicraft and was pleased to see it for 1.7.10 finally only problem is, is that the surface for the tropicraft's tropics water does not show up at all. its not showing the pink and black squares of a missing texture it is just simply invisible as if theres nothing there. once in the water the blue color comes back but above that water nothing can be seen as if its is just air blocks there. this happens in both the tropicraft world and in the over also when I teleported to the tropicraft realm the tiki torches which surround the portal on the for corners also didn't show up but the light from them and the particles from there flame showed up. I did install the mod with a few others, being bibliocraft, carpenters blocks mr crayfish's furniture mod pams harvest craft and two small door mods. I don't think that these would affect the mods textures not showing up but I do plan to remove all mods and resource packs to attempt to see if anything is interfering with each other though when you get the time if perhaps you look into it that would also be greatly appreciated , and of course thanks for the great mod, I appreciate the effort and hard wok. :)

**Comment by Cojomax99** [comment]
I cannot duplicate this issue, try removing the other mods one by one and seeing which is causing this, perhaps?

**Comment by 901327** [comment]
I went through them one by one and I am pretty certain it may have been due to an older optifine not compating with it for some reason, also by the way your mahogany planks texture is the exact same as your palm planks, I don't know if this was intended or not but if not hopefully its not to much of an issue 


     On Saturday, April 25, 2015 7:11 PM, Cojomax99 <notifications@github.com> wrote:
   

 I cannot duplicate this issue, try removing the other mods one by one and seeing which is causing this, perhaps?—

**Comment by Cojomax99** [comment]
Someone pointed out that issue in another...issue. Thanks and glad that it works now :)
