### ISSUE TITLE
BiomeLoadingEvent Clashing with MCDoom

### ISSUE THREAD

**Issue by AzureDoom** [Tropicraft/Tropicraft#414]
## Issue Description
Tropicraft onBiomeLoad is causing an Null point with my own [onBiomeLoad](https://github.com/AzureDoom/MCDoom/blob/forge1.16/src/main/java/mod/azure/doom/util/registry/ModEntitySpawn.java#L15) event. 

## Steps to Reproduce
1) Install Tropicraft along side my MCDoom doom  
2) Try loading world
3) World unable to load

Tropicraft Version:   9.0.1-beta+64  
Forge Version:   36.2.4   

## Game Log
https://gist.github.com/AzureDoom/6379d42481bd6c5b209af0e43521b291

**Comment by Gegy** [comment]
Hmm, this interestingly seems to imply that datapack-loaded biomes don't get a registry name assigned. I'm not sure if this is something we should retroactively apply to our datapack biomes, or if this should rather be considered for MCDoom to handle in the case of datapack biomes? Or alternatively even if this should be considered a Forge issue?

**Comment by AzureDoom** [comment]
I figured out the issue, was on my side on how I did the spawn checks. All fixed now!
