### ISSUE TITLE
Missing config file for 1.16.5

### ISSUE THREAD

**Issue by Nagispace** [Tropicraft/Tropicraft#416]
## Issue Description
There is no config file created making it impossible to change config

Tropicraft Version:   Tropicraft - 9.0.1-beta+64   
Forge Version:   1.16.5-36.2.6

**Comment by NotActuallyTerry** [comment]
Confirmed in 1.15 and 1.16 using latest builds of both.

**Comment by NotActuallyTerry** [comment]
Due to complexity of the fix and end of life support for 1.15, this will not be fixed.
However, it has been fixed going forward.
