### ISSUE TITLE
[1.12.2] Swimming is bugged - get stuck

### ISSUE THREAD

**Issue by Greenknight9000** [Tropicraft/Tropicraft#420]
## Issue Description
So I've made sure this is the effect of Tropicraft and not other mods, and it seems to be down to Tropicraft, but basically if you start swimming as your animation changes, you end up clipping into the floor or walls of the block and become immobile, often leading to you drowning if you don't break the offending block in time

## Steps to Reproduce
1) Go underwater and swim about
2) Go near a block, often near the floor
3) You will find  yourself trapped and unable to move

Tropicraft Version:   tropicraft-MC1.12.2-7.1.9.115
Forge Version:   forge-14.23.5.2855

## Crash log
```
PASTE YOUR CRASH LOG HERE
```

**Comment by NotActuallyTerry** [comment]
We won't be able to provide a fix as we don't support 1.12 anymore. Sorry about that!
