### ISSUE TITLE
I can't craft the Pina colada

### ISSUE THREAD

**Issue by Wisecookie111** [Tropicraft/Tropicraft#425]
## Steps to Reproduce
1)
2)
3)

Tropicraft Version:   
Forge Version:   

## Crash log
```
PASTE YOUR CRASH LOG HERE
```

**Comment by NotActuallyTerry** [comment]
Hey there,

Could you tell us the following:
- Minecraft version
- Tropicraft version
- What you've tried so far to craft it

**Comment by Wisecookie111** [comment]
My Minecraft version is 1.6.5 I used just enough items the mod that shows
you the crafting recipes and everything and no matter what I try to craft
the pina colada I couldn't break down the coconut and I couldn't break down
the pineapple and the chunks so I couldn't craft the pina colada in the end
no matter what I tried it wouldn't work I had to go and create it to get it

**Comment by NotActuallyTerry** [comment]
Alright, could you try crafting a sword and breaking the pineapple with a sword?

**Comment by Wisecookie111** [comment]
Yes that's all the pineapple

**Comment by Wisecookie111** [comment]
Sorry I mistyped That's solve the pineapple problem I still can't break a
coconut though

**Comment by Wisecookie111** [comment]
Never mind thank you I was using a modded sword
