### ISSUE TITLE
Can´t find any ore in the tropics. 

### ISSUE THREAD

**Issue by KirschDealer** [Tropicraft/Tropicraft#43]
I was searching for zircon-ore but it seems like there aren´t any ores. I have also installed buildcraft and flans-mod, does one of these mods affect the spawn of ores in the tropics?

**Comment by Cojomax99** [comment]
Fixed https://github.com/Tropicraft/Tropicraft/commit/484be15eca2c49d77ca4e1c706a8992f48b6aff4.

Will be in v6.0.4.
