### ISSUE TITLE
making pina colaa doesnt work

### ISSUE THREAD

**Issue by minerattdga** [Tropicraft/Tropicraft#432]
## Issue Description
I have all of the required ingredients, coconut pineapple and bamboo mug. when i put it in the crafting table it does not make pina colada. I tried so many different crafting combos. How will I go to the tropics?

## Steps to Reproduce
1)
2)
3)

Tropicraft Version:   
Forge Version:   

## Crash log
```
PASTE YOUR CRASH LOG HERE
``
![Screenshot (930)](https://user-images.githubusercontent.com/100994858/156877231-fd5a0413-e5dd-4811-b71a-b1d6c281e9f4.png)
`

**Comment by NotActuallyTerry** [comment]
Hey there!
Apologies for the delay, but to make a Piña colada you need Pineapple **Chunks**.
To get Chunks, you'll want to break the Pineapple with a sword.
