### ISSUE TITLE
Portal not spawning?

### ISSUE THREAD

**Issue by CitrusOfficial** [Tropicraft/Tropicraft#434]
## Issue Description
I don't know if this is intentional and I'm sorry if I'm wasting your time by not reading into it but I remember and have been seeing that there was a portal associated with getting in and out of this dimension after the first time you use a pina colada but it is not spawning for me, this is kind of of a non issue though as you can just drink another pina colada in the dimension to return to the overworld but I would still like a portal and am confused on if it is intentional or not. 

## Steps to Reproduce
1) launch the game
2)drink pina colada
3) go to dimension no portal spawn

Tropicraft Version:   9.20 also tested on 9.01
Forge Version:   1.16.5

## Crash log no crashes
```
PASTE YOUR CRASH LOG HERE
```

**Comment by NotActuallyTerry** [comment]
Hey!

Unfortunately with the 1.16 version we ran out of time while porting, so weren't able to port over the portal. That'll probably be why you're not seeing it.
Hopefully we can bring it back for 1.18!
