### ISSUE TITLE
Re-add Tropics Portal

### ISSUE THREAD

**Issue by FocusPokeus** [Tropicraft/Tropicraft#435]
[ ] Re-add portal code
[ ] Ensure portals can be destroyed easily (#368)

**Comment by NotActuallyTerry** [comment]
Currently being worked on, please watch #430

**Comment by NotActuallyTerry** [comment]
Portal has been readded in [feature/portal-pois](/Tropicraft/Tropicraft/tree/feature/portal-pois)
