### ISSUE TITLE
mxed up textures

### ISSUE THREAD

**Issue by 901327** [Tropicraft/Tropicraft#44]
I think in your guys haste or maybe just an accidental mix up in the coding but the mahogany planks are using the exact same texture as the palm planks, not sure if this was intended but to be honest another texture for the mahogany planks shouldn't seem to bad of a texture to whip up just change thee color and saturation of one of the original minecraft wooden plank textures till it matches the color of the inside of the mahogany log

**Comment by Cojomax99** [comment]
We just never got a mahogany planks texture is the real issue here. This will be fixed in the upcoming release!
