### ISSUE TITLE
Ashen dont spawn

### ISSUE THREAD

**Issue by MiniGPT** [Tropicraft/Tropicraft#440]
## Issue Description
Ashen dont spawn on 7.1.9.115 version, with the spawner and with random spawns, on R.A.D modpack and isolated instance

## Steps to Reproduce
1) Teleport to topicraft
2) Check home tree
3) Spawner dont work
4) Ashen dont spawn anywere else

Tropicraft Version: 7.1.9.115  
Forge Version: 14.23.5.2859

**Comment by NotActuallyTerry** [comment]
Hey there!

Unfortunately we no longer provide support for Tropicraft v7.1.9.
I would however check the modlist of the modpack for any mods which alter the spawning behavior of mobs, as they can interfere with the spawning of our mobs.
