### ISSUE TITLE
Tropicraft.net potentially compromised

### ISSUE THREAD

**Issue by CrownJoker** [Tropicraft/Tropicraft#441]
## Issue Description
The main webpage of https://tropicraft.net/ appears to have an unintended landing page, and references "Cocytus Services".

Apologies as this is likely not the correct place for this report, just hoping to get someone's eyes on this who is able to contact the site owner.

## Steps to Reproduce
1) open web browser
2) go to https://tropicraft.com/ 
3) confusion

Tropicraft Version:   n/a
Forge Version:   n/a

## Crash log
```
n/a
```

**Comment by NotActuallyTerry** [comment]
Hello, webdev here!

This issue wasn't the result of being compromised, but instead was the result of me not testing things which I change! Remember kids, never test in production!
It should be fixed now

**Comment by CrownJoker** [comment]
My bad, mountains from molehills, should have dug a bit deeper. thanks!
https://aaaaaaaaaaaaaaaaaaaaaaaa.net/
Lol
