### ISSUE TITLE
after using a bucket of tropical fish, it turned to "item.bucket.name" instead of regular bucket, and a crash report

### ISSUE THREAD

**Issue by abidoang** [Tropicraft/Tropicraft#46]
I was trying to test the tropical fish by spawning it with "fish in a bucket" items. After I spawned them using the corresponding bucket, the bucket turned into item.bucket.name instead of regular bucket. Here's the demonstration of the bug wrapped up in a gif: http://imgur.com/ohMHQsZ

And then for some reason, this "bucket" has a recipe using a fluid transposer from Thermal Expansion 3 and it'll turn into a fluid named "fluid.tile.null" (I assume it should be tropics water?) and after being used in the machine, it turned into normal bucket while the fluid got stored into the machine.
<a href="http://imgur.com/1BYqpAD"><img src="http://i.imgur.com/1BYqpAD.png" title="source: imgur.com" /></a>

Another report, this one involves one of the tropical flower: http://pastebin.com/v1DRDZ3q

**Comment by Cojomax99** [comment]
If the tropical flower crash happens in v6.0.4 please re-file a bug for it.
