### ISSUE TITLE
/weather command does not work in the Tropics Realm

### ISSUE THREAD

**Issue by ChaseCarlson** [Tropicraft/Tropicraft#476]
You cannot change the weather using the /weather command in the Tropics Realm.

**Steps to reproduce the behavior:**
1. Enter the Tropics Realm
2. Try to use the /weather command to change the weather
3. Weather doesn't change

**Expected behavior**
If it's raining and I do /weather clear, the rain should stop.
If it's clear and I do /weather rain, the rain should start.

**Versions**
 - Tropicraft Version 9.3.2 (Latest commit)
- Forge Version 40.1.0

**Comment by Tamaized** [comment]
This is a problem for all dimension mods. Vanilla hardcodes the /weather command to only work in the overworld.

There's mods to get around this such as https://github.com/TeamTwilight/CrossDimCommands
