### ISSUE TITLE
Bonemealing Purified Sand doesn't make Seagrass

### ISSUE THREAD

**Issue by NotActuallyTerry** [Tropicraft/Tropicraft#482]
[LT Discord](https://canary.discord.com/channels/444746940761243652/992797246234038332/997877814772629584)

**Comment by jaskarth** [comment]
Whoops- [e150eb5](https://github.com/Tropicraft/Tropicraft/commit/e150eb523aa05e6056e30efea56c04236adf407a) also fixed this!
