### ISSUE TITLE
Allow Tropicraft Chairs, Beach Umbrellas & Beach Floats to be Invulnerable

### ISSUE THREAD

**Issue by NotActuallyTerry** [Tropicraft/Tropicraft#493]

**Comment by Dragon-Seeker** [comment]
In what way? Like only the player can destroy them to be picked up or Invulnerable in the sense of never being able to destroy the item drop?

**Comment by NotActuallyTerry** [comment]
It's for Love Tropics builds, they would need to be summoned or given with an NBT tag. Then once placed, they would not be able to be destroyed unless its with a tool or smth i needw figure that part out

**Comment by Dragon-Seeker** [comment]
Could be if clicked with the debug stick it destroys the entity or something. We could use TrackedData to see if it can be destroyed or not

**Comment by NotActuallyTerry** [comment]
Using the debug stick would work nicely!

**Comment by Dragon-Seeker** [comment]
https://user-images.githubusercontent.com/50533513/183270961-a62ceade-50f3-4553-8050-9b7366b442fa.mp4
