### ISSUE TITLE
Palm trees generating in unusual spots

### ISSUE THREAD

**Issue by NotActuallyTerry** [Tropicraft/Tropicraft#496]
![Image](https://user-images.githubusercontent.com/670020/183239581-3098d6c5-6d27-454c-9d3d-aeaad26b4b45.png)

**Comment by Dragon-Seeker** [comment]
That

**Comment by NotActuallyTerry** [comment]
b982b04 might resolve this bug

**Comment by NotActuallyTerry** [comment]
Unable to find any new tree generation that is unusual, assuming fixed
