### ISSUE TITLE
Turtles are unable to be teleported while being ridden

### ISSUE THREAD

**Issue by NotActuallyTerry** [Tropicraft/Tropicraft#498]

**Comment by Dragon-Seeker** [comment]
Seems to be a Minecraft Bug: https://bugs.mojang.com/browse/MC-102608 and https://bugs.mojang.com/browse/MC-252003

**Comment by NotActuallyTerry** [comment]
Yep, it's a vanilla bug.
Will be suggesting the fix is added to https://github.com/LoveTropics/LTExtras
