### ISSUE TITLE
[1.18.2] Reeds are not destroyed by lava

### ISSUE THREAD

**Issue by Dragon-Seeker** [Tropicraft/Tropicraft#502]
![java_8CoSOFcWRt](https://user-images.githubusercontent.com/50533513/183757108-85dd11ae-e088-4870-a385-3dbbf0ed42fe.png)

**Comment by Dragon-Seeker** [comment]
After further testing, there are some other blocks that I would think lava should break but don't...
![java_nJ9b59ny0P](https://user-images.githubusercontent.com/50533513/184460001-34d6e9ea-57dd-408a-b1ee-159519a4b8f9.png)

Still have no clue what is causing this to happen or not happen

**Comment by Dragon-Seeker** [comment]
~~Might be caused in some part due to the Reed block implementing water loggable~~

Nah seems tied to canBeReplaced() which is based of the blocks material so Idk such is a bug due to many other blocks doing the exact same effect

**Comment by NotActuallyTerry** [comment]
This behaviour lines up with vanilla behaviour for similar plants
