### ISSUE TITLE
(1.12.2) Serious integration issue with SR Parasites and tropics dimension

### ISSUE THREAD

**Issue by alexva12** [Tropicraft/Tropicraft#505]
**Describe the bug**
Attempting to use SRparasites with tropicraft results in exaggerated spawning of parasites in the tropics dimension, even after going through the configs and setting the evolution phase to -2 in the srparasites config (basically, completely disabling all spawning) as well as disabling parasite spawning through incontrol. bug with the tropicraft dimension.

**To Reproduce**
1. Install SRparasites
2. Allow game to load through normal methods
3. Travel to Tropics dimension
4. parasites everywhere even after using incontrol and the srparasite config to disable them

**Expected behavior**
When disabling spawning through incontrol and srparasites, it is expected that there is no spawning of the parasites in the dimension. this has been narrowed down through extensive testing and previous reports from others using both mods to be the tropics dimension being bugged in this sense.

**Screenshots**
![2022-08-15_21 48 49](https://user-images.githubusercontent.com/10392170/184916823-712092f3-905c-4370-b64d-9cc30cd44e7d.png)

**Versions**
 - Tropicraft Version 7.1.9.115
 - Forge Version 14.23.5.2860
 - Minecraft Version 1.12.2

**Crash log**
N/A, does not exist. integration issue.

**Comment by NotActuallyTerry** [comment]
Hey there!

Thank you for the report. Unfortunately we no longer provide support for 1.12, and therefore will not be able to assist in fixing it.
If anybody else would like to provide a fix, please target [TropicraftArchive/1.12.2](https://github.com/Tropicraft/TropicraftArchive/tree/1.12.2)

I'll leave this open for a while so anybody passing can have a chance to see this
