### ISSUE TITLE
Localization improvements

### ISSUE THREAD

**Issue by Adaptivity** [Tropicraft/Tropicraft#51]
Few localization issues:
1) Many Tropicraft entities have missing names. Their names should be added in .lang file.
2) Coffee Berry and Raw Coffee Bean names mismatched. Coffee Berry is Raw Coffee Bean and Raw Coffee Bean is Coffee Berry in-game. Swap their names.
3) Dart and Curare should have independent [effect strings](https://github.com/Tropicraft/Tropicraft/blob/master/src/main/resources/assets/tropicraft/lang/en_US.lang#L280-L286).
And Curare should have something like %s tag which allows me to swap effect with Curare word in Russian localization.

**Comment by Cojomax99** [comment]
These have all been corrected in our 1.10.2 branch. Thanks for pointing these out!
