### ISSUE TITLE
Individual weather from Overworld

### ISSUE THREAD

**Issue by ALainxD** [Tropicraft/Tropicraft#512]
**Is your feature request related to a problem? Please describe.**
I making a modpack that is Winter themend and I made it always snow in the overworld, but due to that it is also always raining in Tropicraft

**Describe the solution you'd like**
A serverside mod setting to make rain and thunder completly gone so it can't even switch to that

**Describe alternatives you've considered**

A clientside setting to remove weather effect visualy 

**Additional context**
I made it already with a biometweaker mod so it doesn't rain, but the sky is still always cloudy, grey and there is no sun

**Comment by NotActuallyTerry** [comment]
This would be quite tricky, because as far as I know weather cycles aren't tied to dimensions. I suppose an option to not have weather display in Tropicraft could be a solution.

@Corosauce thoughts?

**Comment by NotActuallyTerry** [comment]
So the general consensus is that this is rather out of scope for Tropicraft to be fixing, as it's a vanilla issue. However, Coro did find this mod which fixes the issue: https://github.com/Linguardium/DimensionMutability/
Hopefully this fixes it for you!

**Comment by ALainxD** [comment]
Sadly Dimension Mutability was not available for Forge, luckily a friend of mine asked for permission to port the mod to Forge and made it for me.

https://www.curseforge.com/minecraft/mc-mods/dimension-mutability-forge
