### ISSUE TITLE
Generating new chunks smp crash (Village generating Crash)

### ISSUE THREAD

**Issue by voidswrath** [Tropicraft/Tropicraft#53]
When generating new chunks on smp this crash happens. Looks to be when it tries generating a village. Restarting the server fixes it and no village generates http://pastebin.com/wMhZaHPe

**Comment by klangg** [comment]
I'm seeing the same crash on Forge 1448. My guess is that the Tropicraft recommended version of Forge being 1291 is because it has not been updated for the Forge fluid changes. I can provide logs if needed.

**Comment by Cojomax99** [comment]
Interested to see if this is an issue in 1.10.2. If it is, feel free to re-open or create a new issue.

**Comment by voidswrath** [comment]
Haven't used 1.10.2 too much but will give it a go sometime soon maybe
