### ISSUE TITLE
There is too many frogs

### ISSUE THREAD

**Issue by drjaka** [Tropicraft/Tropicraft#54]
I can not walk ten blocks without appearing one sapo to poison me please correct the bug

**Comment by medsouz** [comment]
![](https://33.media.tumblr.com/0415818df2a15eb3b64c45f1c6d278fc/tumblr_mqdni7Wb8u1sbg8zzo1_400.gif)

Glory to the frogs

**Comment by ajloveslily14** [comment]
~~I see no problem here they are poisonous IRL~~

**Comment by Dulciphi** [comment]
I, for one, welcome our new overlords. I ~~prey~~ pray they will teach me to flip 30 body-lengths in a single high-speed bound, as they themselves do. What I find particularly mesmerising is the way they manage to target their foes with God-like precision, even as they cartwheel through the air at near-relativistic speeds. Not to mention their apparent mastery of procreativity. Glory, indeed.

**Comment by Cojomax99** [comment]
Thanks everybody for the comments on this post. Frogs have been nerfed in our 1.10.2 branch. We'll see if the nerf sticks, those frogs are tricky.
