### ISSUE TITLE
when FiddlerCrab spawning. crash games

### ISSUE THREAD

**Issue by baguchi** [Tropicraft/Tropicraft#540]
**Describe the bug**
This bug seem tried to access private field net.minecraft.world.entity.Entity.f_19793_
mayby something on wrong code

**To Reproduce**
1. meet the FiddlerCrab
2. crash

**Versions**
 - Tropicraft Version [9.4.0]
 - Forge Version [48.0.35]
 - Minecraft Version [1.20.1]

**Crash log**

here is a crash log

[crash-2023-06-29_21.32.39-server.txt](https://github.com/Tropicraft/Tropicraft/files/11910750/crash-2023-06-29_21.32.39-server.txt)

**Comment by NotActuallyTerry** [comment]
Fixed by 14df0bd
