### ISSUE TITLE
[1.20.1] Cannot find Koa Village

### ISSUE THREAD

**Issue by Spectralhaunter** [Tropicraft/Tropicraft#552]
I've recently discovered tropicraft being on 1.20.1 and i got so excited however I seem to be unable to find a single koa village! Three games and 3000 blocks in all directions on each and nothing. I saw an old, old post mention a schematic? Or is this a bug? 

I'm playing through curseforge 1.20.1 singleplayer

**Comment by Spectralhaunter** [comment]
Am I ever actually going to get a reply to this? I understand things are busy but it's been a month

**Comment by itsbazke** [comment]
@Spectralhaunter I found one quite immediately, are you in the right dimension?

**Comment by Spectralhaunter** [comment]
I am in the right dimension

**Comment by Gegy** [comment]
@Spectralhaunter Are you able to find the structure by using `/locate structure tropicraft:koa_village`? 🙂 If this is not working either, can you try with only Tropicraft installed in a new world?

**Comment by Spectralhaunter** [comment]
Okay I was able to find one with this thank you I am so sorry for the trouble! I don't know why one was so far away the nearest one was over 3000 blocks away, just bad luck I guess!
