### ISSUE TITLE
Coral looks sad and blocky underwater :(

### ISSUE THREAD

**Issue by BBoldt** [Tropicraft/Tropicraft#56]
![](http://i.imgur.com/FxKlUVC.jpg)

Maybe look into adding support for this mod as well:
http://minecraft.curseforge.com/mc-mods/231659-aquatweaks

**Comment by Dulciphi** [comment]
I love aquatweaks but, even without that, something could be done, no? Mariculture and BoP have somehow avoided the issue with blocky coral - and they're also open source :)

**Comment by BBoldt** [comment]
I've noticed the tropicraft coral looks okay underneath regular water, so it must be something specifically to do with the tropics water.

**Comment by Cojomax99** [comment]
This fix will be in v6.0.5 :)
