### ISSUE TITLE
1.20.1 forge 47.2.16 modpack crash

### ISSUE THREAD

**Issue by Thunderrock424242** [Tropicraft/Tropicraft#572]
**Describe the bug**

**To Reproduce**
1. Go to my modpack and start it with tropicraft enabled

**Expected behavior**
i expected it to not crash

**Screenshots**

**Versions**
 - Tropicraft Version [e.g. 9.6.3]
 - Forge Version [e.g. 47.2.16]
 - Minecraft Version [e.g. 1.20.1]

**Additional context**

**Crash log**
```
Paste your crash log here, or attach it as a file
```
[latest.log](https://github.com/Tropicraft/Tropicraft/files/13668263/latest.log)
[debug.log](https://github.com/Tropicraft/Tropicraft/files/13668264/debug.log)

**Comment by CosmicHikari** [comment]
The attached logs are not crash logs. Please attach `crash-2023-12-13_23.05.13.log`
