### ISSUE TITLE
Cant make glass.

### ISSUE THREAD

**Issue by kappa-ferro** [Tropicraft/Tropicraft#573]
**Describe the bug**
On the wiki it says purified sand can be smelted into glass, but upon putting it in the furnace with fuel nothing happens.

**To Reproduce**
Try to smelt purified sand like normal sand.

**Expected behavior**
The sand is smelted into glass.

**Screenshots**
![tropicraft_glass_bug png](https://github.com/Tropicraft/Tropicraft/assets/80153381/d86f334a-733d-4de2-aae4-35fac9edbdf1)

**Versions**
 - Tropicraft Version [e.g. 9.6.3]
 - Forge Version [e.g. 47.2.0]
 - Minecraft Version [e.g. 1.20.1]

**Additional context**

**Crash log**
```
Paste your crash log here, or attach it as a file
```

**Comment by Cojomax99** [comment]
Has been fixed in all versions Minecraft 1.21 and onward.
