### ISSUE TITLE
Flying glitch related to flippers

### ISSUE THREAD

**Issue by Watchful1** [Tropicraft/Tropicraft#58]
See this video by nihontiger

https://www.youtube.com/watch?v=jW_66nxR1Pg

He was able to free fly out of the water after removing his flippers.

**Comment by Cojomax99** [comment]
Yeah, flippers used to set the player's flying capability. We're working on making the flippers no longer need that capability (creative mode, basically) in order to achieve weightlessness in water.

**Comment by Watchful1** [comment]
Heh, cleaning up old issues I see.

**Comment by Cojomax99** [comment]
Yeah, figured with the big overhaul release coming we may as well tidy up loose ends and make sure everything is in order that wasn't fixed before, so we can stay on top of the issues as they come in this time.
