### ISSUE TITLE
Mod banner patterns won't be displayed

### ISSUE THREAD

**Issue by 5A93** [Tropicraft/Tropicraft#580]
None of mod banner patterns will be displayed after installing the mod. Everything backs to normal after removing the mod

1. Install the mod and some other mod with it's modded banner patterns, like kobolds!
2. Try to customize the banner with those patterns
3. You will find it not display in loom's gui
4. Actually make the banner and deploy it, and you will find the pattern not display on it either

**Expected behavior**
Working like vanilla patterns, which not being effected

**Versions**
 - Tropicraft Version 9.5.2-1.19.2
 - Forge Version 43.3.7
 - Minecraft Version 1.19.2

**Comment by Cojomax99** [comment]
If this is still an issue on the latest version of Minecraft, please feel free to re-open.
