### ISSUE TITLE
[1.18.2] Can't find Koa villages anywhere

### ISSUE THREAD

**Issue by gzu921** [Tropicraft/Tropicraft#582]
I am playing on a Mac with Forge for 1.18.2 and have traveled the tropics a lot without finding a Koa after an hour. 

Mac has a Minecraft folder with mods and config folder, but oddly there is no Tropicraft config file anywhere in the config. I've been playing for a few weeks, though just today went into the Tropics. 

When I entered the Tropics, my hot bar was empty and the horizon was black. I quit the game and rejoined and it fixed that issue. 

I'm happy to provide more details!

**Comment by gzu921** [comment]
Has anybody seen this?

**Comment by Cojomax99** [comment]
Sorry, we are not supporting 1.18.2 anymore. If you find this is still occurring in the latest version of Minecraft, please feel free to re-open.
