### ISSUE TITLE
Block Breaking Problems!

### ISSUE THREAD

**Issue by KaiHampton11** [Tropicraft/Tropicraft#59]
In Tropicraft 6.0.4 From What I Have Been Seeing Bambo Chests And Bambo Fences From This Mod Break So Easily And Dont Use Any Durability On My Axe Which I Would Normally Use To Break Those Kinds Of Blocks But bambo SHoots Auctully Take Longer And Dont Break Instantly Like They Use Too, I Think You Guys Might Of By Acident Changed The Breaking Propities So Please Fix. :-(

**Comment by Malqua** [comment]
Fix #59 @KaiHampton11's keyboard sporadically toggles the Shift key after hitting Space.
