### ISSUE TITLE
Crafting bugs

### ISSUE THREAD

**Issue by AlexandruCimpian** [Tropicraft/Tropicraft#594]
### Tropicraft version

9.6.3

### Minecraft Version

1.20.1

### (Forge / Neo Forge) Version

47.3.0

### Describe the issue

You can't craft thatch door, also the tropicraft version of bamboo fence ain't shown in crafting recipes/creative

### Steps to reproduce

![Screenshot_4774](https://github.com/user-attachments/assets/c671c25c-2e1c-40e4-985b-67381e2741aa)

### Expected behaviour

Craft da door

### Screenshots

![Screenshot_4774](https://github.com/user-attachments/assets/8cfa69f8-8410-4ee1-9f43-cb3e1038880b)

![Screenshot_4778](https://github.com/user-attachments/assets/55ea852d-9d24-416a-b7ea-0d13634bd7d3)

### Log files

.

**Comment by Cojomax99** [comment]
Fixed in commit 5ca84420bd4e3618fb286eeae0c4d0a4fab69384
