### ISSUE TITLE
Drink mixer not working (With coffee at least)

### ISSUE THREAD

**Issue by jzburda** [Tropicraft/Tropicraft#60]
The drink mixer won't allow me to put in coffee beans/water, and a look on the wiki told me to input it near the eyes. However, when I hover over the eye part of the totem, it'll show the information of the block behind it (With WAILA)

**Comment by Cojomax99** [comment]
The drink mixer was definitely buggy in past versions. This is fixed in 1.10.2 and onward. Cheers!

**Comment by joyov12** [comment]
you dumb fuck you're supposed to put a water bucket in the machine ur whalecum :)
