### ISSUE TITLE
Small Boats Mod barely works with Tropicraft water

### ISSUE THREAD

**Issue by ItsMrHexx** [Tropicraft/Tropicraft#61]
When I had Small Boats mod installed, the boats would barely work with the water because of the waves, Anyone know how to fix this?

**Comment by Cojomax99** [comment]
There are no longer any waves in Tropicraft to my knowledge, so I don't know if this issue is valid anymore. Which version were you using?

**Comment by Brycey92** [comment]
The waves are gone and there doesn't appear to be any working version of the Small Boats mod for 1.7.10 anyway. If you have a working copy of the mod, @ItsMrHexx, please either provide it so we can test it, or close the issue.
