### ISSUE TITLE
Indestructible portals

### ISSUE THREAD

**Issue by Yorkforce** [Tropicraft/Tropicraft#64]
Using Tropicraft 6.0.4 within the crundeecraft modpack, the portals that are created make the area surrounding it completely indestructible, this is leading to players having to abandon their bases because they can no longer interact with the surrounding area.

This issue persists even if an op destroys the portal

This is creating issues due to griefers also, its pretty destructive to a servers world folder.

**Comment by Yorkforce** [comment]
After further testing, this is related to the spawn-protection= setting in the server.properties file.
Looking at a previous issue https://github.com/Tropicraft/Tropicraft/issues/19 it would appear the spawn creating error is still present.

**Comment by Cojomax99** [comment]
Fixed the spawn creation error.
