### ISSUE TITLE
add config option to change the time frame needed to get into the tropicraft dimension

### ISSUE THREAD

**Issue by atm397** [Tropicraft/Tropicraft#65]
So we can input our own time values to be at any time we want and as short or long as we want. I want it to be able to get it to work in conjunction with a mod I'm using that changes the length of the day but I think it would be useful for others as well.

**Comment by Cojomax99** [comment]
There is currently no variable that tells us how long the day cycle is that I know of. Unless we have this, then there's no feasible way for us to detect when actual 'sunset' is. Right now we base it on the idea that a day is 24000 ticks. So unless there is a variable for that somewhere I can't find, there's not really much we can do. Sorry :( :person_frowning:
