### ISSUE TITLE
Tropicraft water buckets: item.bucket.name; not working correctly

### ISSUE THREAD

**Issue by Maleia** [Tropicraft/Tropicraft#67]
Running: 
Forge 10.13.4.1448 (1.7.10)
tropicraft 6.0.5
(and several others)

We take a bucket, scoop up tropic water, bucket turns into item.bucket.name tropicraft:bucketTropicraftWater, we can not place water on the ground.  When looking into the NBT data for the bucket, we notice that the bucket has normal NBT data such as:

Count, Slot, Damage, ID  (checking against other buckets such as lava and molten iron, these have only those fields).

When we pull in a creative mode tropic water bucket, we notice that it's NBT data contains additional information:

tag -> Fluid -> Amount:1000, FluidName: tropicswater

We are able to place the tropic water from the creative-mode bucket into the world without issue, but trying to pick it back up results in the same issue as above.

**Comment by SvEgiiVEteR** [comment]
I have the same error forge 1614

**Comment by Cojomax99** [comment]
This is fixed in the upcoming release. And if it's not, we'll need a new issue for it as this is for a now outdated version of the mod we aren't supporting anymore.
