### ISSUE TITLE
special sands generate in weird 1x1 chunk squares

### ISSUE THREAD

**Issue by BBoldt** [Tropicraft/Tropicraft#68]
![](http://i.imgur.com/QtwZMQD.jpg)
![](http://i.imgur.com/RVmof85.jpg)

**Comment by BBoldt** [comment]
here is another screenshot illustrating the issue:
![](http://i.imgur.com/6OpyFnK.jpg)

**Comment by Malqua** [comment]
[Looks like a feature to me.](http://www.travelandleisure.com/slideshows/worlds-strangest-beaches/2)

**Comment by BBoldt** [comment]
@Malqua The one in that pic doesn't look square to me. :P 

Here are some more real world examples:
![](http://i.imgur.com/Il2P1MC.png)
![](http://i.imgur.com/pfjTyJy.png)

Maybe the special Tropicraft sands could generate as whole islands with specific sand colors rather than single chunks filled with them.

**Comment by Malqua** [comment]
It was a joke. The real world also isn't rendered in chunks.

**Comment by DashFury** [comment]
They want to make the type of sand biome specific, but it's not implemented yet. The piece of code dealing with that is currently in the `replaceBlocksForBiome` method of the `ChunkProviderTropicraft` class, but should be moved to the biome generation instead, according to the comment accompanying the said method:
`public void replaceBlocksForBiome(int x, int z, Block[] blocks, byte[] metas, BiomeGenBase[] biomes) //TODO: Move to biomes`

**Comment by Cojomax99** [comment]
For now and upcoming releases, these sands will be used as a supplement to existing gen features like coral and seaweed. For now, there will not be different types of sand beaches, but we're not ruling it out for the future.
