### ISSUE TITLE
Tropicraft mineral issues (Crafting)

### ISSUE THREAD

**Issue by Rainstar77** [Tropicraft/Tropicraft#69]
* Minecraft Version : 1.7.10
* Forge Version : Forge10.13.4.1448-1.7.10
* Tropicraft Version : 6.0.5
* installed mods ; TMI, Tropicraft, Rei's Minimap, RoadWorks

Hello, I found some crafting errors in Tropicraft Mod. Here some screenshots.
(Don't care about Korean. This is my mother tongue.)

![azurite error1](https://cloud.githubusercontent.com/assets/14582699/9996653/f5014dfc-60c2-11e5-81a6-1c1eeb829913.png)
![zircon error1](https://cloud.githubusercontent.com/assets/14582699/9996754/7c2f0ea4-60c3-11e5-9d81-72a376986931.png)
Zircornium Block is crafted by 9 Azurite Crystal or 9 Zircon Crystal.

And...

![eudialyte error1](https://cloud.githubusercontent.com/assets/14582699/9996806/d0938844-60c3-11e5-804e-5845233f9228.png)
Azurite Block is crafted by 9 Eudialyte Shards.

Plus, These blocks can't change to item? For Examples...

![zirconium error2](https://cloud.githubusercontent.com/assets/14582699/9996917/6fb9d324-60c4-11e5-8389-97fbc46385c4.png)
![azurite error2](https://cloud.githubusercontent.com/assets/14582699/9996918/717f4c66-60c4-11e5-90b5-c8c985cbd307.png)
Lastly, these blocks can break punching.

**Comment by DashFury** [comment]
I have the same problem. I temporarily fixed it using Minetweaker, which let you register new recipes through a script.

Here is the script, if it can help anybody until a fix is made. It has to be put in the "scripts" directory, in a ".zs" file, if you have Minetweaker.

    # Remove the broken recipes
    recipes.remove(<tropicraft:tile.blockOre:*>);
    
    # Add the correct ones:
    # Eudialyte Block
    recipes.addShaped(<tropicraft:tile.blockOre:0>, [
        [<tropicraft:ore:0>, <tropicraft:ore:0>, <tropicraft:ore:0>],
        [<tropicraft:ore:0>, <tropicraft:ore:0>, <tropicraft:ore:0>],
        [<tropicraft:ore:0>, <tropicraft:ore:0>, <tropicraft:ore:0>]
    ]);

    # Zircon Block
    recipes.addShaped(<tropicraft:tile.blockOre:1>, [
        [<tropicraft:ore:1>, <tropicraft:ore:1>, <tropicraft:ore:1>],
        [<tropicraft:ore:1>, <tropicraft:ore:1>, <tropicraft:ore:1>],
        [<tropicraft:ore:1>, <tropicraft:ore:1>, <tropicraft:ore:1>]
    ]);

    # Azurite Block
    recipes.addShaped(<tropicraft:tile.blockOre:2>, [
        [<tropicraft:ore:2>, <tropicraft:ore:2>, <tropicraft:ore:2>],
        [<tropicraft:ore:2>, <tropicraft:ore:2>, <tropicraft:ore:2>],
        [<tropicraft:ore:2>, <tropicraft:ore:2>, <tropicraft:ore:2>]
    ]);

    # Block of Cubic Zirconium
    recipes.addShaped(<tropicraft:tile.blockOre:3>, [
        [<tropicraft:ore:3>, <tropicraft:ore:3>, <tropicraft:ore:3>],
        [<tropicraft:ore:3>, <tropicraft:ore:3>, <tropicraft:ore:3>],
        [<tropicraft:ore:3>, <tropicraft:ore:3>, <tropicraft:ore:3>]
    ]);

    # Recipes to change back those blocks into crystals:
    recipes.addShapeless(<tropicraft:ore:0> * 9, [<tropicraft:tile.blockOre:0>]);
    recipes.addShapeless(<tropicraft:ore:1> * 9, [<tropicraft:tile.blockOre:1>]);
    recipes.addShapeless(<tropicraft:ore:2> * 9, [<tropicraft:tile.blockOre:2>]);
    recipes.addShapeless(<tropicraft:ore:3> * 9, [<tropicraft:tile.blockOre:3>]);

**Comment by Rainstar77** [comment]
Thanks to comment this issue.
Unfotunately I never heard the program (or mod?). So I searched Web and knew what Minetweaker is just now. I'll try to fix the issue using this program, but I can't be convinced that I could use that very well. I think the program is a little complex.

**Comment by DashFury** [comment]
It's a mod, so you just have to put it in your "mods" folder. The script has to go into the script directory, which is itself in your game directory, and should be created by the mod anyway.

They have a really detailed wiki if you want: http://minetweaker3.powerofbytes.com/wiki/Tutorial:Introduction

**Comment by Rainstar77** [comment]
Thanks for fixing this problem, though it a little late. I'm looking forward to updated version soon.
