### ISSUE TITLE
TropiCraft doing something very weird with biome IDs

### ISSUE THREAD

**Issue by ReikaKalseki** [Tropicraft/Tropicraft#70]
For some reason, [my biome ID conflict checker](https://github.com/ReikaKalseki/DragonAPI/blob/master/Auxiliary/Trackers/BiomeCollisionTracker.java#L24) does not pick up conflicts with your biomes, no matter their IDs. It has never failed before, and I do not see how it could, assuming the biomes are properly registered.

Additionally, some users are reporting that other ID conflict checkers are also failing to catch your biomes, which cements the idea that something is weird on your end.

Are you doing something weird with biomes (like not registering it to BiomeGenBase, or doing so in postLoad)?

Given that biome ID conflicts are world-corrupting problems, this needs to be fixed.

**Comment by Malqua** [comment]
Feel free to make a branch, fix the issue, and submit a PR.

**Comment by Cojomax99** [comment]
The biomes are registered here: https://github.com/Tropicraft/Tropicraft/blob/master/src/main/java/net/tropicraft/world/biomes/BiomeGenTropicraft.java#L49-L57

If there is an issue, then it is with ConfigMod, but I'm not really sure what issue there would be.
