### ISSUE TITLE
Tropicraft Exception Getting Block Into World

### ISSUE THREAD

**Issue by jredfox** [Tropicraft/Tropicraft#75]
crashed using 4g giving 5g
http://pastebin.com/3gr9RHZ2

**Comment by Corosauce** [comment]
Appears to be thehippomaster.aquaticabyss.AAWorldGen.generateRocks generating chunks in tropicraft world, potentially causing a recursive loop due to it not checking if a chunk exists before it tries to generate outside of the chunk it was supposed to generate in.

**Comment by jredfox** [comment]
The  other time it stock overflowed and somehow pastebin.com edited my crash report on what I pasted and java stock overflow at the head didn't show up .

**Comment by Corosauce** [comment]
The mod that does that rock gen isn't ours, report that error to the owner of that mod, probably this: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2151604-aquatic-abyss-swordfish-and-serpents-v1-1-1

**Comment by jredfox** [comment]
Yeh I know but, adding any terain gen to tropicraft makes it sound like it crashes. So could you add an option in the config to allow modification to the tropics?
