### ISSUE TITLE
Too many Frogs causing Lag and somethings wrong with biome conflict 

### ISSUE THREAD

**Issue by CitiesXL2815** [Tropicraft/Tropicraft#76]
Everytime I go to the tropics all the frog start spawning cause the game to lag, my FPS drops to zero and sometimes crashes, it says out of memory then crashes, even trying solve the problem doesn't work, like Peaceful, Butcher from WE and magnum torches, they still spawn, there getting very annoying. Can you reduce the Mobs from spawning lots. plus Tropic Biome is Conflicting with Biomes O Plenty and spawning in the Overworld

**Comment by CitiesXL2815** [comment]
B:genTropicraftInOverworld=true do i change this to false so it stops spawning the tropics in the overworld?

**Comment by Cojomax99** [comment]
I'm not sure why the frogs would spawn like that - it may be another mid interfering with our spawning mechanics. Also, yes, that is what that setting would do.

**Comment by Cojomax99** [comment]
Mob spawning is a bit odd in the tropics, but we have a fix and a plan for upcoming releases. Fear not!
