### ISSUE TITLE
Crash when looking up recipes to make purple dye

### ISSUE THREAD

**Issue by UndeadZeratul** [Tropicraft/Tropicraft#77]
Crash Report: http://pastebin.com/xpyK4HBH

Forge v1558
Tropicraft v6.0.4

**Comment by Cojomax99** [comment]
Please try v6.0.5 here: http://tropicraft.net/downloads/

v6.0.4 has a bug with NEI that caused this crash sometimes.

Cheers!

**Comment by UndeadZeratul** [comment]
I saw there was an update and I'm trying that now; will let you know what I find.

**Comment by Cojomax99** [comment]
:+1:
