### ISSUE TITLE
No mobs or animals are spawning in the tropical dimension.

### ISSUE THREAD

**Issue by Icanhazwafle** [Tropicraft/Tropicraft#79]
Me and a group of friends set up a modpack using curse and saw that it didnt have tropicraft so we decided to manually add it. We added it correctly so we decided to test it to see if there was a problem and when we entered the tropical dimension we noticed it was completely barren of life. No animals or mobs (except ashen warriors) spawn at all and ashen warriors only spawn when spawned via spawner. Also we tested if it was the animals themselves and no they all worked well it was just that they werent spawning.

**Comment by medsouz** [comment]
Are you on peaceful difficulty?

**Comment by Icanhazwafle** [comment]
No.

**Comment by medsouz** [comment]
Are there any errors in the console? I also need a list of mods in your pack.

**Comment by Icanhazwafle** [comment]
AE2, AnimatioAPI, Another One Bites the Dust, Applied Energistics 2, Balkon's WeaponMod, Bdlib, BetterFps, BigReactors- 0.4.3A, Blood Magic, Brandon's Core, Buildcraft, Buildcraft Compact, Carpenter's Blocks, Chisel 2, ChiselTones, Chromaticraft, CodeChickenCore, CoFH Core, CoFHLib, ComputerCraft, coroutil-1.1.2, Custom Mob Spawner, Death Counter, DecoCraft2, Dense Ores, DoggyStyle, Draconic Evolution, DragonAPI, Enchanting Plus, Ender Storage, EnderCore, Extra Utilities, ExtraCells2, ExtraTic, Falling Meteors Mod, FastLeafDecay, Flaxbeard's Steam Power, Guide-API, Hardcore Ender Expansion, Highlands, Infinibows (Infinity Bow Fix), Inventory Pets, Inventory Tweaks, JourneyMap, LookingGlass, Malisis Core, Malisis Doors, Mantle, Metallurgy, Metallurgy Core, Minechem, Minefactory Reloaded, Mo'Creatures, Morpheus, Mouse Tweaks, MrCrayfish's Furniture Mod, Mystcraft, NEI Integration, Nei Mystcraft Plugin, NetherOres, NotEnoughtItems, Openblocks, OpenModsLib, OreDictionaryConverter, Pam's Harvestcraft, Project Red-Base, Project Red- Compat, Project Red Fabrication, Project Red- Integration, Project Red- Lighting, Project Red- Mechanical, Project Red- World, ProjectE, Railcraft, Redstone Armory, Redstone Arsenal, Roguelike Dungeons, Runic Dungeons, Sanguimancy, SecretRoomsMod, Simply Jetpacks, SpACore, Steve's Carts 2, Technomancy, Thaumcraft, Thaumcraft Inventory Scanning, Thaumcraft Mob Aspects, Thaumcraft NEI Plugin, Thaumcraft Node Tracker, Thaumic Energetics, Thaumcraft Expansion, Thermal Foundation, Tinkers Construct, Treecapitator, Tropicraft-6.0.4, Waila, Waila Harvestability, Waila Plugins, Wawla- What Are We Looking At, Witchery, Ztones, Zyin's Hud.

There were no errors that I saw.

**Comment by Cojomax99** [comment]
I suspect Custom Mob Spawner may have an issue with our custom biomes, but I am not sure how to confirm that. Also just so you are aware, Tropicraft latest is v6.0.5, which contains several nice bug fixes.

**Comment by Icanhazwafle** [comment]
ok thank you. Where can i find the latest version?

**Comment by medsouz** [comment]
[Tropicraft v6.0.5](http://bit.ly/tropicraftv605)

**Comment by Icanhazwafle** [comment]
It was Custom Mob Spawner. Thank you for you time.

**Comment by medsouz** [comment]
Glad we could help. :smile:
