### ISSUE TITLE
Where's verion 6.0.5?

### ISSUE THREAD

**Issue by B1ackRibbon** [Tropicraft/Tropicraft#81]
I can't find version 6.0.5 in the downloads list.

EDIT: I found it by editing the link https://tropicraft.net/download/ to https://tropicraft.net/downloads/
it seems to be a problem with the website.

**Comment by Cojomax99** [comment]
There is 'downloads' and an 'old downloads' page.

v6.0.5 is on the 'downloads' page currently since it is the latest version: https://tropicraft.net/downloads/

**Comment by Bogdan-G** [comment]
@Cojomax99 depending on how the link if the main page the user sees it:
http://imgur.com/5o9N7Gx
instead it: http://imgur.com/Y5XJZKJ

**Comment by ProsperCraft** [comment]
I can confirm clicking download gives the 6.0.4 version still.
