### ISSUE TITLE
No Ashen Masks

### ISSUE THREAD

**Issue by A-nonny-mouse** [Tropicraft/Tropicraft#82]
Hi, I'd like to report that my Tropicraft has missing ashen masks. My mods include:
-Biomes O'Plenty
-Optifine
-Tropicraft and
-Coroutil
and I use a mac. What might the issue be? Or are they not available in the creative inventory?

![2015-12-29_21 01 19](https://cloud.githubusercontent.com/assets/16476602/12034671/56990af6-ae6f-11e5-8f1d-daeada0ae0c0.png)

**Comment by Cojomax99** [comment]
Hi! Sorry, we never added wearable ashen masks into the latest version of Tropicraft. I believe this is because we never could get the rendering quite right on them for users in 1.7.10.

Relevant code: https://github.com/Tropicraft/Tropicraft/blob/master/src/main/java/net/tropicraft/entity/hostile/EntityLostMask.java#L131

**Comment by cbaakman** [comment]
This is strange! It seems that all the code for the masks is present in the item registry, with working textures. Simply uncommenting the code in the lost mask entity makes them drop once again. I haven't noticed any bugs.

Is there a reason why it's still commented out?

**Comment by Cojomax99** [comment]
Same reason I mentioned as above, probably, which is that rendering on players is not in place. We used to use Coremods to do that, but those are frowned upon now, so we decided not to implement them.

**Comment by 210099** [comment]
Hi guys,
Sorry for the inconvenience, but I just want to ask, how do you look into and uncomment the code? I want to do this because I'm interested in re-adding the ashen masks just for decoration.
Thank you

**Comment by cbaakman** [comment]
You can checkout this github branch, and change the following: https://github.com/cbaakman/Tropicraft/commit/adb22cbb9ba8284ddebb0fd817a7b2138483b005
Then compile with eclipse.

However, this change simply makes the ashen masks drop, I noticed. They cannot be placed on the walls anymore. They are equipable as head gear, but that feature doesn't look finished.

**Comment by Cojomax99** [comment]
This is fixed in 1.10.2.
