### ISSUE TITLE
Tropical Fish are Very broken

### ISSUE THREAD

**Issue by Erinbutt** [Tropicraft/Tropicraft#84]
It seems like tropical fish are very broken:
-Spawning is almost non-existant (along with many other creatures)
- Fish swim in a very jerky and strange manner. At times they will switch between their state while on land and how the should be in the water. 
- When placed from a bucket, they will merely sit on top of the water instead of swimming.
- They also survive out of the water

I am using the latest version of forge, and optifine along with a few other mods.
Thanks!

**Comment by B1ackRibbon** [comment]
Same problem here as well as an item.bucket.name glitch that I'm still getting on the latest version.

**Comment by Cojomax99** [comment]
Fish are fixed in the upcoming release. This is now outdated, so I'm closing it.
