### ISSUE TITLE
item.bucket.name bug still not fixed

### ISSUE THREAD

**Issue by B1ackRibbon** [Tropicraft/Tropicraft#85]
I made this bug report a couple weeks ago and I haven't gotten a response. I am using the latest version of Tropicraft (6.0.5) and I still get this bug - Every time I use an empty bucket on tropics water, it becomes "item.bucket.name" and is useless.

**Comment by Brycey92** [comment]
This is a duplicate issue of #83. Please remove it and continue discussion there.
