### ISSUE TITLE
Too many frogs and iguanas spawning in overworld

### ISSUE THREAD

**Issue by Robotmassacre538** [Tropicraft/Tropicraft#94]
I have a really big modpack, and something I noticed after adding tropicraft is that a huge amount of frogs and iguanas are spawning in the overworld causing a lot of lag and poisoning, I would have no issue with this glitch if it was in the dimension but it's in the overworld, I tried doing gentropicraftinoverworld = false in the configs but even after wiping out all the mobs in the area they just spawn right back, pleas help, I don't want to remove this mod

**Comment by CitiesXL2815** [comment]
Tweak the Biomes id, those id's are conflicting with biome's O Plenty, it worked for me. But the lag with the frogs and iguanas will be left for Cojo and other awesome Dev's to fix or tweak

**Comment by YannikPipek** [comment]
Maybe add a config for the mob spawning?
