### ISSUE TITLE
Can't enter the tropics

### ISSUE THREAD

**Issue by helmet12** [Tropicraft/Tropicraft#96]
every time i drink the colada it loads flashs the world for half a second and then loads me into a portal beside my chair i was sitting in in the overworld.

**Comment by gurico1999** [comment]
Make a chair
Place the chair
At sunset, drink the Pina Coloda
Out of the portal
Not a tropical. I don’t load.   :(

**Comment by Cojomax99** [comment]
@gurico1999 You need to sink to the bottom of the portal and wait until you are teleported.

@helmet12 That's odd...I've never heard of it flashing the world for half a second. Does the loading screen come up at all?

**Comment by IvanSokolovBG** [comment]
I have the same issue. I sit in the chair, drink a pina colada at sunset (i set the time at 13000 ticks) and it starts the terrain download. My PC is slow so it takes some time, and exactly at the moment i spawn, I'm alredy at the bottom of the portal and it teleports me back. With this, the portal NEVER works again with just sinking to the bottom to teleport. I need to drink another pina colada at the bottom so it teleports me to the tropical dimension(and vice-versa).

**Comment by gurico1999** [comment]
It is a portal to this world.
Challenge was to make a lot of the world.
I got the idea.
Drink at the bottom of the portal.
I finally went to the tropical.

**Comment by IvanSokolovBG** [comment]
It's cool you got there. Maybe the spawn should change and instead of spawning in the portal you could spawn near it? I know it destroies the idea, but this is a real big issue...
Now if I can ask you for a favor - if you find any villages in the tropics, can you send me the seed and the coordinates? I'm having a real hard time finding one and I think it's a bug...I have posted the issue here in the issue section and I'm waiting for the developer to notice it. Check it out if you want to.
Cheers!

**Comment by gurico1999** [comment]
==== IvanSokolovBG ====
That’s too bad.
I find villages the seed　-2733537960593266173
Good Luck & enjoy Tropi Life

**Comment by IvanSokolovBG** [comment]
I wasn't able to find any villages....Looked around 40-50 minutes and got to almost 5000 blocks away from spawn, yet no luck. I'm waiting for Cojo to help me out :)

**Comment by gurico1999** [comment]
Do you have placed in the directory ?
TCSchematics is koavillagedate

**Comment by IvanSokolovBG** [comment]
Yes. I have done as in the instructions! check the thread --> https://github.com/Tropicraft/Tropicraft/issues/108

**Comment by gurico1999** [comment]
I'm like good luck
There is a village in sight from home in that seed .
![2016-06-03_15 07 03](https://cloud.githubusercontent.com/assets/13464774/15805170/aece6616-2b5c-11e6-8a97-968e0cd9e9e2.png)

**Comment by IvanSokolovBG** [comment]
Can you give me the coordinates of the village? also can you give me the coordinates and a picture of your spawn point?
