### ISSUE TITLE
wrong materials set for tropicraft blocks

### ISSUE THREAD

**Issue by cbaakman** [Tropicraft/Tropicraft#99]
Some tropicraft blocks have the wrong materials set in the java code. For example: Bamboo blocks are set to be stone and are broken with a pickaxe, rather than an axe. Thatch blocks, don't drop themselves when broken, but simply disappear with one short click.

Also the step sounds could also use adjustments. Coral sand and purified sand sound like stone when broken. So do fruit tree saplings.

**Comment by Cojomax99** [comment]
We are looking into this to ensure it is not an issue in the upcoming release. Thanks!
